INSERT INTO public.question_bank (exam_name, subject, topic, difficulty, text, options, correct, explanation, source, year) VALUES

-- SURGERY (44 questions)
('INICET','Surgery','General Surgery','medium','A 45-year-old male presents with a painless lump in the neck for 3 months. On examination, the lump moves on swallowing. The most likely diagnosis is:','["Thyroglossal cyst","Branchial cyst","Cervical lymphadenopathy","Thyroid nodule"]',3,'A lump that moves on swallowing indicates attachment to the laryngotracheal complex, consistent with a thyroid nodule. Thyroglossal cysts move on protrusion of tongue.','Bailey & Love Surgery',2022),

('INICET','Surgery','General Surgery','hard','A patient with obstructive jaundice has the following: bilirubin 15 mg/dL, ALP markedly elevated, GGT elevated, ALT mildly elevated. The next investigation of choice is:','["ERCP","MRCP","Liver biopsy","CT abdomen"]',1,'MRCP (Magnetic Resonance Cholangiopancreatography) is the non-invasive investigation of choice for biliary obstruction. It provides excellent anatomical detail without radiation or contrast.','Bailey & Love Surgery',2023),

('INICET','Surgery','Surgical Oncology','hard','A 55-year-old female has carcinoma of the breast with axillary lymph node involvement. The most important prognostic factor is:','["Tumor size","Number of lymph nodes involved","ER/PR receptor status","Grade of tumor"]',1,'The number of axillary lymph nodes involved is the single most important prognostic factor in breast carcinoma. It determines stage and guides adjuvant therapy.','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Gastrointestinal Surgery','medium','A patient presents with Courvoisier sign (palpable gallbladder with painless jaundice). The most likely cause is:','["Gallstone disease","Carcinoma head of pancreas","Primary sclerosing cholangitis","Acute cholecystitis"]',1,'Courvoisier law states: if the gallbladder is palpable in a jaundiced patient, the jaundice is unlikely due to gallstones. Carcinoma head of pancreas is the most common cause.','Bailey & Love Surgery',2022),

('INICET','Surgery','Thoracic Surgery','hard','A 30-year-old male has a tension pneumothorax. The immediate management is:','["Chest X-ray confirmation","Needle decompression at 2nd ICS MCL","Intercostal drain insertion","Intubation and ventilation"]',1,'Tension pneumothorax is a clinical diagnosis. Immediate needle decompression at 2nd intercostal space, midclavicular line is life-saving. Do NOT wait for X-ray.','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Vascular Surgery','medium','A 65-year-old diabetic male presents with rest pain in the foot, non-healing ulcer, and ABI of 0.4. The best treatment is:','["Limb amputation","Angioplasty/revascularization","Anticoagulation","Hyperbaric oxygen"]',1,'ABI < 0.5 indicates severe peripheral arterial disease. Revascularization (angioplasty or bypass) is the treatment of choice to save the limb before considering amputation.','Bailey & Love Surgery',2022),

('INICET','Surgery','Colorectal Surgery','hard','Duke staging for colorectal carcinoma: Duke B means:','["Tumor confined to mucosa","Tumor through all layers of bowel wall, nodes negative","Lymph node metastasis","Distant metastasis"]',1,'Duke B: tumor extends through all layers of the bowel wall (through muscularis propria or beyond) but lymph nodes are negative. Duke C involves lymph nodes.','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Hepatobiliary Surgery','medium','The most common site for carcinoma of the gallbladder is:','["Fundus","Body","Neck","Cystic duct"]',0,'Carcinoma of the gallbladder most commonly arises in the fundus (60%), followed by body and neck. It is associated with gallstones in 70-90% of cases.','Bailey & Love Surgery',2022),

('INICET','Surgery','Trauma Surgery','hard','A patient with abdominal trauma has free fluid in the abdomen on FAST (Focused Assessment with Sonography for Trauma). He is hemodynamically unstable. Next step:','["CT abdomen","Emergency laparotomy","Diagnostic peritoneal lavage","Observation"]',1,'Hemodynamically unstable patient with positive FAST requires emergency exploratory laparotomy. CT scan is only appropriate for stable patients.','ATLS Manual',2022),

('INICET','Surgery','Urology','medium','The most common malignant tumor of the kidney in adults is:','["Transitional cell carcinoma","Renal cell carcinoma","Wilms tumor","Lymphoma"]',1,'Renal cell carcinoma (clear cell type most common) accounts for 85% of all kidney cancers in adults. It arises from the proximal tubular epithelium.','Campbell Walsh Urology',2022),

('INICET','Surgery','Endocrine Surgery','hard','A patient has MEN type 2A. Which of the following is NOT a component?','["Medullary thyroid carcinoma","Pheochromocytoma","Hyperparathyroidism","Insulinoma"]',3,'MEN 2A consists of: medullary thyroid carcinoma, pheochromocytoma, and hyperparathyroidism. Insulinoma is part of MEN 1 (along with parathyroid adenoma and pituitary tumor).','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Breast Surgery','medium','Paget disease of the nipple is associated with:','["Benign breast disease","Underlying breast carcinoma","Eczema","Sebaceous cyst"]',1,'Paget disease of the nipple is a form of intraepithelial carcinoma and is associated with underlying invasive or in situ breast carcinoma in nearly all cases.','Bailey & Love Surgery',2022),

('INICET','Surgery','Hernia','easy','The most common type of hernia is:','["Femoral hernia","Umbilical hernia","Indirect inguinal hernia","Direct inguinal hernia"]',2,'Indirect inguinal hernia is the most common hernia overall (accounts for 50% of all hernias). It passes through the deep inguinal ring lateral to the inferior epigastric vessels.','Bailey & Love Surgery',2022),

('INICET','Surgery','Hernia','hard','Littre hernia contains:','["Meckel diverticulum","Appendix","Richter hernia","Sliding hernia"]',0,'Littre hernia contains a Meckel diverticulum within the hernial sac. Amyand hernia contains the appendix. Richter hernia involves only part of the bowel circumference.','Bailey & Love Surgery',2022),

('INICET','Surgery','Burns','hard','A patient has burns covering both lower limbs and the perineum. Using the Rule of Nines, the total BSA burned is:','["27%","37%","47%","36%"]',1,'Each lower limb = 18% × 2 = 36%. Perineum = 1%. Total = 37%. Accurate BSA calculation guides fluid resuscitation (Parkland formula).','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Plastic Surgery','medium','The most common cause of Dupuytren contracture is:','["Trauma","Idiopathic/genetic","Diabetes","Alcoholism"]',1,'Dupuytren contracture (palmar fibromatosis) is primarily idiopathic/genetic in origin, though associated with diabetes, epilepsy, alcoholic liver disease, and trauma.','Bailey & Love Surgery',2022),

('INICET','Surgery','Neurosurgery','hard','An epidural hematoma is most commonly caused by:','["Bridging vein rupture","Middle meningeal artery injury","Superior sagittal sinus injury","Cortical vein rupture"]',1,'Epidural (extradural) hematoma results from middle meningeal artery injury, classically following temporal bone fracture. It shows a biconvex (lenticular) lesion on CT.','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Orthopedic Surgery','medium','Colles fracture involves:','["Distal radius with dorsal displacement","Distal ulna","Smith fracture","Scaphoid"]',0,'Colles fracture is a fracture of the distal radius with dorsal displacement of the distal fragment, volar tilt, and radial deviation — producing the "dinner fork" deformity.','Bailey & Love Surgery',2022),

('INICET','Surgery','Gastrointestinal Surgery','hard','Whipple procedure (pancreaticoduodenectomy) is the operation of choice for:','["Carcinoma body of pancreas","Carcinoma head of pancreas","Insulinoma of tail","Pseudocyst of pancreas"]',1,'Whipple procedure (pancreaticoduodenectomy) is performed for carcinoma of the head of pancreas, periampullary carcinoma, and duodenal carcinoma. Tail lesions require distal pancreatectomy.','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Surgical Anatomy','hard','The artery of Drummond (marginal artery of colon) is formed by anastomosis of:','["Superior and inferior mesenteric arteries","Celiac and SMA","Right and left colic arteries only","SMA and internal iliac"]',0,'The marginal artery of Drummond runs along the inner margin of the colon and is formed by anastomosis between branches of the superior mesenteric artery (SMA) and inferior mesenteric artery (IMA).','Gray''s Anatomy',2020),

('INICET','Surgery','Hepatobiliary Surgery','hard','Child-Pugh score does NOT include:','["Bilirubin","Prothrombin time","AFP level","Ascites"]',2,'Child-Pugh score includes: bilirubin, albumin, prothrombin time (INR), ascites, and hepatic encephalopathy. AFP (Alpha-fetoprotein) is a tumor marker, not part of Child-Pugh scoring.','Schwartz Principles of Surgery',2023),

('INICET','Surgery','Vascular Surgery','medium','The most common site for atherosclerotic aneurysm is:','["Thoracic aorta","Abdominal aorta infrarenal","Iliac arteries","Femoral artery"]',1,'Abdominal aortic aneurysm (AAA) most commonly occurs in the infrarenal segment (below the renal arteries), which is hemodynamically the most susceptible region.','Bailey & Love Surgery',2022),

('INICET','Surgery','Urology','hard','A 5-year-old child has Wilms tumor (nephroblastoma). The most common presenting symptom is:','["Hematuria","Abdominal mass","Hypertension","Fever"]',1,'Wilms tumor most commonly presents as an asymptomatic abdominal mass discovered by the parent or during routine examination. Hematuria occurs in only 25% of cases.','Campbell Walsh Urology',2022),

('INICET','Surgery','Colorectal Surgery','medium','The most common site for sigmoid volvulus is:','["Cecum","Sigmoid colon","Transverse colon","Splenic flexure"]',1,'Sigmoid volvulus is the most common form of colonic volvulus (accounts for 70-80%). It typically occurs in elderly, institutionalized, or chronically constipated patients.','Bailey & Love Surgery',2022),

('INICET','Surgery','Surgical Infection','hard','The organism most commonly responsible for gas gangrene is:','["Clostridium perfringens","Clostridium tetani","Bacteroides fragilis","Staphylococcus aureus"]',0,'Gas gangrene (clostridial myonecrosis) is most commonly caused by Clostridium perfringens (welchii), which produces alpha toxin (lecithinase) causing massive tissue destruction.','Bailey & Love Surgery',2022),

-- MEDICINE (44 questions)
('INICET','Medicine','Cardiology','hard','A 60-year-old male has ST elevation in leads II, III, and aVF. The artery most likely involved is:','["Left anterior descending","Right coronary artery","Left circumflex","Left main coronary"]',1,'ST elevation in inferior leads (II, III, aVF) indicates inferior wall MI, supplied by the right coronary artery (RCA) in 80% of cases, and by the left circumflex in 20%.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Neurology','hard','A patient presents with ascending paralysis starting from legs, areflexia, and albuminocytological dissociation in CSF. The diagnosis is:','["Multiple sclerosis","Guillain-Barre syndrome","Myasthenia gravis","Transverse myelitis"]',1,'Guillain-Barre syndrome features ascending paralysis, areflexia, and albuminocytological dissociation (high protein with normal cell count) in CSF. The most common variant is AIDP.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Pulmonology','medium','A patient has exudative pleural effusion. All of the following criteria (Light criteria) apply EXCEPT:','["Pleural/serum protein ratio > 0.5","Pleural LDH > 200 IU/L","Pleural/serum LDH ratio > 0.6","Pleural glucose > serum glucose"]',3,'Light criteria for exudate: pleural/serum protein > 0.5, pleural/serum LDH > 0.6, or pleural LDH > 2/3 upper limit of normal serum LDH. Glucose is low in exudates (TB, malignancy, empyema), not high.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Gastroenterology','hard','The most common cause of portal hypertension in India is:','["Cirrhosis","Non-cirrhotic portal fibrosis","Budd-Chiari syndrome","Portal vein thrombosis"]',1,'Non-cirrhotic portal fibrosis (NCPF) — also called idiopathic portal hypertension — is the most common cause of portal hypertension in India, unlike Western countries where cirrhosis predominates.','Harrison''s Principles of Internal Medicine',2023),

('INICET','Medicine','Nephrology','hard','The most common cause of nephrotic syndrome in adults is:','["Minimal change disease","Focal segmental glomerulosclerosis","Membranous nephropathy","IgA nephropathy"]',2,'Membranous nephropathy is the most common cause of idiopathic nephrotic syndrome in adults (accounts for 30-40%). Minimal change disease is the most common cause in children.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Hematology','hard','A patient has pancytopenia, hypercellular bone marrow, and teardrop cells on peripheral smear. The diagnosis is:','["Aplastic anemia","Myelofibrosis","Megaloblastic anemia","Leukemia"]',1,'Myelofibrosis features pancytopenia, hypercellular then hypocellular marrow, and teardrop (dacrocyte) cells on peripheral smear due to extramedullary hematopoiesis and fibrosis.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Endocrinology','medium','Chvostek sign and Trousseau sign are seen in:','["Hyperkalemia","Hypocalcemia","Hypomagnesemia","Both B and C"]',3,'Both hypocalcemia and hypomagnesemia can cause neuromuscular irritability manifesting as Chvostek sign (facial twitch on tapping) and Trousseau sign (carpal spasm with BP cuff). Hypomagnesemia also causes hypocalcemia.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Rheumatology','hard','A 30-year-old female has joint pain, butterfly rash, and anti-dsDNA antibodies. The most specific antibody for this condition is:','["ANA","Anti-dsDNA","Anti-Smith","Anti-Ro/SSA"]',2,'Anti-Smith (anti-Sm) antibody is the most specific antibody for Systemic Lupus Erythematosus (SLE), though anti-dsDNA is both sensitive and specific and correlates with disease activity.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Infectious Disease','hard','A patient from endemic area has fever, hepatosplenomegaly, pancytopenia, and positive bone marrow for LD bodies. The treatment is:','["Metronidazole","Amphotericin B liposomal","Doxycycline","Quinine"]',1,'Visceral leishmaniasis (Kala-azar) is diagnosed by LD (Leishman-Donovan) bodies in bone marrow. Liposomal amphotericin B is the treatment of choice, especially in India due to resistance to antimonials.','Harrison''s Principles of Internal Medicine',2023),

('INICET','Medicine','Cardiology','medium','The most common cause of sudden cardiac death in young athletes is:','["Dilated cardiomyopathy","Hypertrophic obstructive cardiomyopathy","Myocarditis","Long QT syndrome"]',1,'Hypertrophic obstructive cardiomyopathy (HOCM) is the most common cause of sudden cardiac death in young athletes in the United States. It features asymmetric septal hypertrophy.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Pulmonology','hard','A patient has dyspnea, hypoxemia, PaO2/FiO2 < 200, bilateral infiltrates, and no evidence of cardiac failure. The diagnosis is:','["Pulmonary embolism","ARDS","Pulmonary edema","Severe pneumonia"]',1,'ARDS (Acute Respiratory Distress Syndrome) is defined by: acute onset, PaO2/FiO2 < 200 mmHg, bilateral infiltrates on CXR, and PCWP < 18 or no clinical evidence of left atrial hypertension.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Nephrology','medium','The most common cause of acute kidney injury in ICU patients is:','["Prerenal azotemia","Acute tubular necrosis","Contrast nephropathy","Acute glomerulonephritis"]',1,'Acute tubular necrosis (ATN) is the most common cause of AKI in hospitalized patients, usually due to ischemia or nephrotoxins. It causes muddy brown granular casts in urine.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Gastroenterology','medium','The investigation of choice for hepatocellular carcinoma surveillance is:','["CT abdomen","MRI liver","Ultrasound abdomen with AFP","PET scan"]',2,'For HCC surveillance in cirrhotic patients, ultrasound abdomen every 6 months with AFP measurement is recommended. AFP > 400 ng/mL with a liver mass is diagnostic without biopsy.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Hematology','hard','In sickle cell disease, which type of crisis is most common?','["Aplastic crisis","Vaso-occlusive (painful) crisis","Sequestration crisis","Hemolytic crisis"]',1,'Vaso-occlusive (painful) crisis is the most common type of crisis in sickle cell disease, caused by sickling of RBCs blocking microvascular flow, especially in bones, chest, and abdomen.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Dermatology','medium','Nikolsky sign is positive in:','["Pemphigus vulgaris","Bullous pemphigoid","Dermatitis herpetiformis","Epidermolysis bullosa"]',0,'Nikolsky sign (rubbing normal skin causes blister formation) is positive in pemphigus vulgaris because the split is intraepidermal (suprabasal). It is negative in bullous pemphigoid (subepidermal split).','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Neurology','medium','The most sensitive test for detecting early Alzheimer disease is:','["CT brain","MRI brain","FDG-PET scan","Amyloid PET"]',3,'Amyloid PET scan can detect amyloid plaques years before clinical symptoms in Alzheimer disease. FDG-PET shows temporoparietal hypometabolism. MRI shows hippocampal atrophy.','Harrison''s Principles of Internal Medicine',2023),

('INICET','Medicine','Endocrinology','hard','A patient with type 1 diabetes develops hypoglycemia unawareness. The most appropriate management is:','["Increase insulin dose","Relaxation of glycemic targets temporarily","Switch to oral hypoglycemics","Continuous glucose monitoring only"]',1,'Hypoglycemia unawareness (autonomic failure) occurs with frequent hypoglycemic episodes. Treatment involves relaxation of glycemic targets and avoidance of hypoglycemia for several weeks to restore counter-regulatory response.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Infectious Disease','hard','A patient has fever, rash beginning on wrists and ankles spreading centrally, and tick exposure history. The best empirical treatment is:','["Amoxicillin","Doxycycline","Ciprofloxacin","Ceftriaxone"]',1,'Rocky Mountain Spotted Fever (RMSF) caused by Rickettsia rickettsii presents with the classic triad. Doxycycline is the drug of choice, started empirically without waiting for confirmatory tests.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Pulmonology','medium','The most common cause of massive hemoptysis in India is:','["Bronchogenic carcinoma","Pulmonary tuberculosis","Bronchiectasis","Mitral stenosis"]',1,'In India, pulmonary tuberculosis (and its sequelae like bronchiectasis) is the most common cause of massive hemoptysis. Rasmussen aneurysm (pulmonary artery erosion in TB cavity) can cause fatal hemoptysis.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Rheumatology','medium','The gold standard investigation for sacroiliitis in ankylosing spondylitis is:','["X-ray sacroiliac joints","CT sacroiliac joints","MRI sacroiliac joints","Bone scan"]',2,'MRI of sacroiliac joints is the gold standard for detecting early sacroiliitis in ankylosing spondylitis, detecting bone marrow edema (active inflammation) before structural changes visible on X-ray.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Cardiology','hard','A patient with atrial fibrillation has a CHA2DS2-VASc score of 3. The recommended treatment is:','["Aspirin alone","No antithrombotic therapy","Oral anticoagulation","Aspirin + clopidogrel"]',2,'CHA2DS2-VASc score ≥ 2 in males (≥ 3 in females) indicates high stroke risk in AF, warranting oral anticoagulation (NOACs preferred over warfarin). Score 3 clearly requires anticoagulation.','Harrison''s Principles of Internal Medicine',2022),

('INICET','Medicine','Gastroenterology','hard','Barrett esophagus is defined as:','["Squamous metaplasia in stomach","Intestinal metaplasia in esophagus","Columnar metaplasia in esophagus","Goblet cell hyperplasia in stomach"]',1,'Barrett esophagus is replacement of squamous epithelium in the lower esophagus with specialized intestinal metaplasia (columnar epithelium with goblet cells), a premalignant condition for esophageal adenocarcinoma.','Harrison''s Principles of Internal Medicine',2022),

-- OBSTETRICS & GYNAECOLOGY (44 questions)
('INICET','Obstetrics & Gynaecology','Obstetrics','hard','A primigravida at 38 weeks has blood pressure 160/110, proteinuria 3+, and thrombocytopenia. The diagnosis is:','["Gestational hypertension","Pre-eclampsia","HELLP syndrome","Eclampsia"]',2,'HELLP syndrome (Hemolysis, Elevated Liver enzymes, Low Platelets) is a severe variant of pre-eclampsia. Thrombocytopenia differentiates it from pre-eclampsia alone.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','hard','The most common site of endometriosis is:','["Ovary","Rectovaginal septum","Fallopian tube","Uterosacral ligament"]',0,'The ovary is the most common site of endometriosis, often forming endometriomas (chocolate cysts). The characteristic appearance is hemorrhagic cysts containing old blood.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','medium','The Bishop score assesses:','["Fetal well-being","Cervical favorability for induction","Gestational age","Placental position"]',1,'Bishop score assesses cervical favorability for induction of labor, evaluating: dilation, effacement, station, consistency, and position of the cervix. Score > 8 indicates favorable cervix.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','hard','A 40-year-old woman has menorrhagia with submucous fibroid 3 cm. The treatment of choice is:','["Hysterectomy","Hysteroscopic myomectomy","GnRH agonists","Tranexamic acid"]',1,'For submucous fibroids causing menorrhagia in a woman desiring uterine conservation, hysteroscopic myomectomy is the treatment of choice. It provides relief with minimal invasiveness.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','hard','Kleihauer-Betke test is used to detect:','["Rh incompatibility","Feto-maternal hemorrhage","ABO incompatibility","Neural tube defects"]',1,'Kleihauer-Betke test detects fetal red blood cells in maternal circulation (feto-maternal hemorrhage). It is used to determine the dose of anti-D immunoglobulin needed after sensitizing events.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','medium','The most common ovarian tumor in pregnancy is:','["Dermoid cyst (mature teratoma)","Serous cystadenoma","Endometrioma","Mucinous cystadenoma"]',0,'Dermoid cyst (mature cystic teratoma) is the most common ovarian tumor encountered in pregnancy, accounting for about 40% of cases. It has a risk of torsion during pregnancy.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','hard','A patient at 32 weeks gestation has placenta previa with active bleeding. The management is:','["Emergency caesarean section","Expectant management with betamethasone","Cervical cerclage","Tocolysis"]',0,'Major placenta previa with active bleeding at 32 weeks requires emergency caesarean section regardless of gestational age, as maternal safety takes priority over fetal maturity.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','hard','Meigs syndrome consists of:','["Ovarian fibroma, ascites, pleural effusion","Ovarian cyst, ascites, hydrothorax","Uterine fibroid, ascites, pleural effusion","Endometriosis, ascites, pleural effusion"]',0,'Meigs syndrome: ovarian fibroma (benign solid tumor) + ascites + pleural effusion. It resolves after removal of the fibroma. CA-125 may be elevated.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','medium','The most common cause of postpartum hemorrhage is:','["Retained placenta","Uterine atony","Genital tract lacerations","Coagulation disorders"]',1,'Uterine atony (failure of uterine contraction) accounts for approximately 80% of postpartum hemorrhage cases. It is also called the "Tone" component of the 4 Ts (Tone, Tissue, Trauma, Thrombin).','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','hard','CIN III (Cervical Intraepithelial Neoplasia III) is characterized by:','["Extension into endocervix","Full thickness epithelial involvement without stromal invasion","Microinvasion into stroma","Koilocytes in upper third"]',1,'CIN III (severe dysplasia/carcinoma in situ) shows full-thickness involvement of the cervical epithelium by dysplastic cells without stromal invasion. It is a mandatory precursor to invasive cervical cancer.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','hard','The first line tocolytic drug for preterm labor is:','["Ritodrine","Nifedipine","Indomethacin","Magnesium sulfate"]',1,'Nifedipine (calcium channel blocker) is currently the first-line tocolytic agent for preterm labor due to efficacy, oral administration, and favorable side effect profile.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','medium','The most specific marker for epithelial ovarian cancer is:','["CA-125","CEA","AFP","HE4"]',0,'CA-125 (Cancer Antigen 125) is the most commonly used tumor marker for epithelial ovarian cancer, elevated in 80% of advanced-stage disease. HE4 is more specific but less commonly used.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','medium','Shoulder dystocia is managed by all EXCEPT:','["McRoberts maneuver","Fundal pressure","Suprapubic pressure","Wood screw maneuver"]',1,'In shoulder dystocia management: McRoberts maneuver (hyperflexion of maternal thighs), suprapubic pressure, Wood screw maneuver, and Rubin maneuver are used. Fundal pressure is CONTRAINDICATED as it worsens impaction.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','hard','A 25-year-old woman has primary amenorrhea, absent uterus, and 46,XY karyotype. The diagnosis is:','["Turner syndrome","Swyer syndrome","MRKH syndrome","Androgen insensitivity syndrome"]',3,'Androgen insensitivity syndrome (AIS): 46,XY karyotype, absent uterus/fallopian tubes (absent due to MIS), blind vaginal pouch, female phenotype, testes in inguinal canal or labia. Due to defective androgen receptor.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','hard','Biophysical profile score: the maximum possible score is:','["8","10","12","16"]',1,'Biophysical profile (BPP) consists of: fetal breathing movements, gross body movements, fetal tone, reactive NST, and amniotic fluid volume, each scored 0 or 2. Maximum = 10.','Williams Obstetrics',2022),

('INICET','Obstetrics & Gynaecology','Gynaecology','medium','The most common symptom of endometrial carcinoma is:','["Dysmenorrhea","Postmenopausal bleeding","Vaginal discharge","Pelvic mass"]',1,'Postmenopausal bleeding (PMB) is the cardinal symptom of endometrial carcinoma, occurring in 90% of cases. Any PMB should be investigated with transvaginal ultrasound and endometrial sampling.','Williams Gynecology',2022),

('INICET','Obstetrics & Gynaecology','Obstetrics','hard','A pregnant woman at 28 weeks has oligohydramnios (AFI 3 cm). The most common fetal cause is:','["Renal agenesis","Posterior urethral valves","Renal dysplasia","IUGR"]',3,'IUGR (intrauterine growth restriction) due to uteroplacental insufficiency is the most common cause of oligohydramnios in the third trimester. Renal agenesis (Potter sequence) causes severe oligohydramnios earlier.','Williams Obstetrics',2022),

-- PAEDIATRICS (44 questions)
('INICET','Paediatrics','Neonatology','hard','A neonate born at 35 weeks has respiratory distress, grunting, and chest X-ray shows "ground glass" appearance with air bronchograms. The diagnosis is:','["Meconium aspiration","Transient tachypnea of newborn","Hyaline membrane disease (RDS)","Congenital pneumonia"]',2,'Respiratory Distress Syndrome (HMD) affects premature infants due to surfactant deficiency. Ground glass appearance with air bronchograms is the classic X-ray finding.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Nutrition','easy','The recommended duration of exclusive breastfeeding is:','["3 months","4 months","6 months","12 months"]',2,'WHO recommends exclusive breastfeeding for the first 6 months of life, followed by continued breastfeeding with complementary foods until 2 years or beyond.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Developmental Pediatrics','medium','The age at which a child can draw a circle is:','["18 months","2 years","3 years","4 years"]',2,'Drawing a circle is a developmental milestone achieved at 3 years. At 2 years, children can draw a vertical line. At 4 years, they can draw a square.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Infectious Disease','hard','A child has high fever, strawberry tongue, rash starting at neck and spreading downward, desquamation of fingertips, and positive ASO titer. The causative organism is:','["Staphylococcus aureus","Group A Streptococcus","Streptococcus pneumoniae","Measles virus"]',1,'Scarlet fever is caused by Group A Streptococcus (Streptococcus pyogenes) producing erythrogenic toxin. Features: strawberry tongue, sandpaper rash, Pastia lines, desquamation.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Nephrology','hard','A 5-year-old child has edema, proteinuria > 3.5 g/day, hypoalbuminemia, and hyperlipidemia. The first-line treatment is:','["Cyclophosphamide","Prednisolone","Tacrolimus","Rituximab"]',1,'Nephrotic syndrome in children is treated with prednisolone (oral steroids) as first-line therapy. Most cases are minimal change disease and respond to steroids (steroid-sensitive nephrotic syndrome).','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Hematology','hard','A 10-year-old child has pallor, jaundice, splenomegaly, and peripheral smear shows spherocytes. The diagnosis is:','["Sickle cell disease","Hereditary spherocytosis","Thalassemia major","Autoimmune hemolytic anemia"]',1,'Hereditary spherocytosis: autosomal dominant defect in spectrin/ankyrin causing spherocytic RBCs on peripheral smear, positive osmotic fragility test, negative DAT (Coombs test), and splenomegaly.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Neonatology','medium','The most common cause of neonatal jaundice in the first 24 hours of life is:','["Physiological jaundice","ABO incompatibility","Rh incompatibility","G6PD deficiency"]',2,'Neonatal jaundice in the first 24 hours is always pathological. Rh incompatibility is the most common cause, though ABO incompatibility is more frequent but milder.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Respiratory','medium','Croup (laryngotracheobronchitis) is most commonly caused by:','["Haemophilus influenzae","Parainfluenza virus","RSV","Influenza virus"]',1,'Croup is most commonly caused by Parainfluenza virus type 1, followed by types 2 and 3. It causes subglottic edema producing the characteristic "steeple sign" on X-ray and barking cough.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Genetics','hard','A child has intellectual disability, small testes after puberty, tall stature, gynecomastia, and 47,XXY karyotype. The diagnosis is:','["Down syndrome","Klinefelter syndrome","Turner syndrome","Fragile X syndrome"]',1,'Klinefelter syndrome (47,XXY) features: small testes, azoospermia, tall stature, gynecomastia, learning difficulties. It is the most common sex chromosome aneuploidy.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Cardiology','hard','A neonate has cyanosis that improves on crying. The diagnosis is:','["Tetralogy of Fallot","Choanal atresia","Transposition of great arteries","Critical pulmonary stenosis"]',1,'Choanal atresia: cyanosis worse at rest (neonates are obligatory nasal breathers), improves on crying (mouth breathing). Diagnosis confirmed by inability to pass NG tube through nares.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Nutrition','hard','Kwashiorkor differs from Marasmus in having:','["Muscle wasting","Edema","Growth retardation","Decreased total body fat"]',1,'Kwashiorkor (protein deficiency): edema, fatty liver, skin changes, hair changes, but better preserved weight due to edema. Marasmus (calorie deficiency): severe muscle and fat wasting, no edema.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Neurology','medium','The drug of choice for absence seizures (petit mal) in children is:','["Valproate","Phenytoin","Carbamazepine","Ethosuximide"]',3,'Ethosuximide is the drug of choice for pure absence seizures. Valproate is used when absence seizures coexist with generalized tonic-clonic seizures. Phenytoin and carbamazepine can worsen absence seizures.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Gastroenterology','medium','Intussusception most commonly occurs at which location?','["Ileoileal","Ileocecal","Jejunoileal","Colocolic"]',1,'Ileocecal intussusception is the most common type (80-90% of cases), where the terminal ileum invaginates into the cecum/colon. It presents with colicky pain, "currant jelly" stool, and sausage-shaped mass.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Immunology','hard','X-linked agammaglobulinemia (Bruton disease) is characterized by:','["Absent T cells","Absent B cells and immunoglobulins","Low NK cells","Absent complement"]',1,'Bruton agammaglobulinemia: X-linked, absent circulating B cells due to defect in Bruton tyrosine kinase (BTK), absent immunoglobulins. Presents after 6 months when maternal IgG wanes. Recurrent bacterial infections.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Neonatology','hard','The Apgar score assesses all of the following EXCEPT:','["Heart rate","Respiratory effort","Muscle tone","Blood pressure"]',3,'Apgar score (0-2 each): Heart rate, Respiratory effort, Muscle tone, Reflex irritability, Color. Blood pressure is NOT part of the Apgar score. Maximum = 10.','Nelson Textbook of Pediatrics',2023),

('INICET','Paediatrics','Endocrinology','medium','Congenital hypothyroidism on neonatal screening shows:','["Low TSH, low T4","High TSH, low T4","Low TSH, high T4","Normal TSH, low T4"]',1,'Primary congenital hypothyroidism: high TSH (pituitary response to low thyroid hormone) and low T4. Neonatal screening measures TSH; values > 20 mU/L require further evaluation.','Nelson Textbook of Pediatrics',2023),

-- ENT / OTORHINOLARYNGOLOGY (43 questions)
('INICET','ENT','Otology','hard','A patient presents with unilateral conductive hearing loss, tympanic membrane intact, and type As curve on tympanometry. The diagnosis is:','["Otosclerosis","Otitis media with effusion","Tympanosclerosis","Ossicular chain disruption"]',0,'Otosclerosis causes conductive hearing loss (or mixed), intact TM, type As (shallow) tympanogram due to stiffness of the ossicular chain. Carhart notch at 2000 Hz on audiogram is pathognomonic.','Dhingra ENT',2022),

('INICET','ENT','Otology','medium','The most common organism causing Chronic Suppurative Otitis Media (CSOM) tubo-tympanic type is:','["Pseudomonas aeruginosa","Streptococcus pyogenes","Staphylococcus aureus","Proteus mirabilis"]',0,'Pseudomonas aeruginosa is the most common organism isolated in CSOM (both tubo-tympanic and atticoantral types). It produces enzymes that perpetuate the infection.','Dhingra ENT',2022),

('INICET','ENT','Rhinology','hard','A patient has nasal polyps, chronic sinusitis, and aspirin sensitivity. The triad is called:','["Kartagener triad","Samter triad (Widal triad)","Woakes syndrome","Mounier-Kuhn syndrome"]',1,'Samter triad (Aspirin triad/Widal syndrome): nasal polyps + bronchial asthma + aspirin (NSAID) sensitivity. Due to cyclooxygenase pathway disruption causing excess leukotriene production.','Dhingra ENT',2022),

('INICET','ENT','Laryngology','hard','Reinke edema is associated with:','["Voice overuse","Smoking","Vocal nodules","GERD"]',1,'Reinke edema (polypoid corditis) is strongly associated with heavy cigarette smoking. It causes bilateral polypoid swelling of the vocal cords producing a low-pitched hoarse voice.','Dhingra ENT',2022),

('INICET','ENT','Otology','hard','Cholesteatoma is best diagnosed by:','["Pure tone audiometry","CT temporal bone (HRCT)","MRI temporal bone","Tympanometry"]',1,'HRCT of temporal bone (axial and coronal views) is the investigation of choice for cholesteatoma, showing soft tissue mass in the middle ear/mastoid with bone erosion.','Dhingra ENT',2022),

('INICET','ENT','Head and Neck','medium','The most common parotid gland tumor is:','["Pleomorphic adenoma","Warthin tumor","Mucoepidermoid carcinoma","Acinic cell carcinoma"]',0,'Pleomorphic adenoma (mixed parotid tumor) is the most common parotid gland tumor (70-80% of all salivary gland tumors). Despite being benign, it can undergo malignant transformation.','Dhingra ENT',2022),

('INICET','ENT','Rhinology','medium','Killian incision is used in:','["Caldwell-Luc operation","Submucous resection (SMR) of septum","Functional endoscopic sinus surgery","Ethmoidectomy"]',1,'Killian incision (through the mucocartilaginous junction) is used in submucous resection (SMR) of the nasal septum. It preserves the L-shaped cartilage support at the front of the nose.','Dhingra ENT',2022),

('INICET','ENT','Otology','hard','A 70-year-old diabetic presents with severe otalgia, granulation tissue at the bony-cartilaginous junction, and facial nerve palsy. The diagnosis is:','["Malignant (necrotizing) otitis externa","Acute mastoiditis","Cholesteatoma with complication","Temporal bone carcinoma"]',0,'Malignant (necrotizing) otitis externa is caused by Pseudomonas aeruginosa in elderly diabetics/immunocompromised. Granulation tissue at bony-cartilaginous junction of EAC is pathognomonic. Can cause skull base osteomyelitis and cranial nerve palsies.','Dhingra ENT',2022),

('INICET','ENT','Laryngology','medium','The most common site for cancer of the larynx is:','["Supraglottis","Glottis","Subglottis","Transglottis"]',1,'Glottic carcinoma is the most common laryngeal carcinoma. It presents early with hoarseness, has good prognosis due to sparse lymphatics, and is strongly associated with smoking.','Dhingra ENT',2022),

('INICET','ENT','Rhinology','hard','A patient has nasal obstruction, epistaxis, and proptosis. Endoscopy shows a mass in the nasopharynx. The most likely diagnosis in a 16-year-old male is:','["Angiofibroma","Squamous cell carcinoma","Lymphoma","Rhabdomyosarcoma"]',0,'Juvenile nasopharyngeal angiofibroma (JNA) is a benign but locally aggressive vascular tumor occurring exclusively in adolescent males. Presents with unilateral nasal obstruction and spontaneous epistaxis.','Dhingra ENT',2022),

('INICET','ENT','Otology','medium','Weber test lateralizes to the affected side in:','["Sensorineural hearing loss","Conductive hearing loss","Mixed hearing loss","Normal hearing"]',1,'In Weber test, sound lateralizes to the affected (poorer) ear in conductive hearing loss (bone conduction is enhanced due to masking effect), and to the better (normal) ear in sensorineural hearing loss.','Dhingra ENT',2022),

('INICET','ENT','Head and Neck','hard','The drug of choice for angiofibroma is:','["Radiotherapy","Surgery after pre-operative embolization","Chemotherapy","Steroids"]',1,'Treatment of juvenile nasopharyngeal angiofibroma is surgical resection, preceded by pre-operative angiographic embolization (24-48 hours before surgery) to reduce intraoperative blood loss.','Dhingra ENT',2022),

('INICET','ENT','Laryngology','hard','The indication for tracheotomy in epiglottitis is:','["Stridor","Drooling","Respiratory distress not responding to treatment","Thumb sign on X-ray"]',2,'Epiglottitis (usually H. influenzae type b in children) can cause life-threatening airway obstruction. Tracheotomy or intubation is indicated when there is severe respiratory distress not responding to medical treatment.','Dhingra ENT',2022),

('INICET','ENT','Rhinology','medium','The most common cause of epistaxis in children is:','["Hypertension","Digital trauma in Little area","Angiofibroma","Blood dyscrasias"]',1,'Little area (Kiesselbach plexus) on the anteroinferior nasal septum is the most common site of epistaxis. In children, digital trauma (nose picking) is the most common cause.','Dhingra ENT',2022),

('INICET','ENT','Otology','hard','Acoustic neuroma (vestibular schwannoma) most commonly arises from:','["Cochlear nerve","Inferior vestibular nerve","Superior vestibular nerve","Facial nerve"]',1,'Acoustic neuroma (vestibular schwannoma) most commonly arises from the inferior vestibular nerve (60%), less commonly from the superior vestibular nerve. It arises at the Scarpa ganglion, usually in the internal auditory canal.','Dhingra ENT',2022),

-- OPHTHALMOLOGY (43 questions)
('INICET','Ophthalmology','Glaucoma','hard','The most common type of glaucoma worldwide is:','["Acute angle closure glaucoma","Primary open angle glaucoma","Secondary glaucoma","Congenital glaucoma"]',1,'Primary open angle glaucoma (POAG) is the most common type worldwide. It is asymptomatic until late stages, characterized by elevated IOP, open anterior chamber angle, optic nerve cupping, and visual field defects.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Retina','hard','A 60-year-old hypertensive has sudden painless loss of vision, fundus shows "blood and thunder" appearance. The diagnosis is:','["Central retinal artery occlusion","Central retinal vein occlusion","Diabetic retinopathy","Retinal detachment"]',1,'CRVO presents with sudden painless vision loss. Fundus shows diffuse flame hemorrhages in all four quadrants with disc edema - "blood and thunder" or "stormy sky" appearance.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Cornea','medium','Keratoconus is characterized by:','["Flattening of cornea","Conical protrusion of cornea","Horizontal oval cornea","Corneal edema"]',1,'Keratoconus is a progressive non-inflammatory corneal ectasia with conical protrusion of the central cornea. Features: Munson sign, Fleischer ring (iron deposits), Vogt striae, scissor reflex on retinoscopy.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Strabismus','medium','The most common type of squint is:','["Esotropia","Exotropia","Hypertropia","Hypotropia"]',0,'Esotropia (convergent squint) is the most common type of strabismus in children. The most common form is accommodative esotropia due to uncorrected hypermetropia.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Anterior Segment','hard','Fuchs heterochromic iridocyclitis is characterized by all EXCEPT:','["Unilateral","Heterochromia","Keratic precipitates","Posterior synechiae"]',3,'Fuchs heterochromic iridocyclitis: unilateral, fine stellate KPs throughout endothelium, heterochromia, complicated cataract, secondary open angle glaucoma. Notably ABSENT: posterior synechiae (no anterior inflammatory adhesions), no flare/cells.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Retina','hard','Laser treatment in diabetic retinopathy is indicated in:','["Background diabetic retinopathy","Macular edema","Mild non-proliferative DR","Simple microaneurysms"]',1,'Clinically significant macular edema (CSME) and proliferative diabetic retinopathy are indications for laser photocoagulation. Macular edema is treated with focal/grid laser or anti-VEGF injections.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Glaucoma','medium','Goldmann applanation tonometer measures IOP on the principle of:','["Imbert-Fick law","Pascal principle","Mackay-Marg principle","Non-contact principle"]',0,'Goldmann applanation tonometer operates on the Imbert-Fick law: the pressure inside a sphere equals the force necessary to flatten its surface divided by the area of flattening.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Neuro-Ophthalmology','hard','A patient has ptosis, miosis, and anhidrosis on one side. The diagnosis is:','["CN III palsy","Horner syndrome","Myasthenia gravis","Internuclear ophthalmoplegia"]',1,'Horner syndrome (oculosympathetic paresis): ptosis + miosis + anhidrosis (triad). Due to interruption of sympathetic pathway. Anhidrosis indicates lesion in first or second neuron (central or preganglionic).','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Orbit','medium','The most common primary orbital tumor in adults is:','["Capillary hemangioma","Cavernous hemangioma","Dermoid cyst","Lymphoma"]',1,'Cavernous hemangioma is the most common benign orbital tumor in adults, presenting as slowly progressive painless proptosis. On MRI, it shows homogeneous enhancement.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Uvea','hard','The most common intraocular malignancy in adults is:','["Retinoblastoma","Choroidal melanoma","Metastatic carcinoma","Lymphoma"]',2,'Metastatic carcinoma is actually the most common intraocular malignancy overall. Choroidal melanoma is the most common PRIMARY intraocular malignancy in adults.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Cornea','hard','Corneal graft rejection is characterized by:','["Khodadoust line","Coat line","Fleischer ring","Stockers line"]',0,'Khodadoust line (endothelial rejection line) is a line of inflammatory cells on the corneal endothelium migrating across a corneal graft, indicating endothelial rejection.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Pediatric Ophthalmology','hard','Retinopathy of prematurity is most commonly seen in babies born below:','["34 weeks","32 weeks","30 weeks","28 weeks"]',1,'ROP threshold for screening: < 32 weeks gestation OR birth weight < 1500g (or 1500-2000g with unstable course). Most severe ROP occurs in the most premature infants.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Neuro-Ophthalmology','medium','A patient has bitemporal hemianopia. The lesion is at:','["Optic nerve","Optic chiasm","Optic tract","Lateral geniculate body"]',1,'Bitemporal hemianopia (loss of both temporal visual fields) is caused by a lesion at the optic chiasm, where the crossing nasal fibers from both eyes are disrupted. Pituitary adenoma is the most common cause.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Glaucoma','hard','Normal tension glaucoma (NTG) is characterized by:','["IOP always > 21 mmHg","Optic nerve damage with normal IOP","No visual field defects","No disc cupping"]',1,'Normal tension glaucoma (NTG): optic nerve cupping and visual field loss despite IOP consistently < 21 mmHg. Associated with vasospasm, nocturnal hypotension, and systemic vascular disease.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Retina','medium','The gold standard for diagnosis of retinal detachment is:','["Direct ophthalmoscopy","B-scan ultrasound","Indirect ophthalmoscopy","OCT"]',2,'Indirect ophthalmoscopy (binocular indirect ophthalmoscope) with scleral indentation is the gold standard for diagnosis and examination of the peripheral retina and retinal detachment.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Anterior Segment','hard','Arcus senilis is a deposit of:','["Cholesterol/lipids","Calcium","Uric acid","Protein"]',0,'Arcus senilis (gerontoxon) is a white/grey peripheral corneal opacity due to lipid deposits (cholesterol, phospholipids, triglycerides) in the corneal stroma. When unilateral or in young patients, investigate for hyperlipidemia.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Cataract','medium','The most common type of cataract in adults worldwide is:','["Posterior subcapsular","Nuclear cataract (nuclear sclerosis)","Cortical cataract","Anterior subcapsular"]',1,'Nuclear cataract (nuclear sclerosis) is the most common type of age-related cataract worldwide, causing myopic shift in early stages, then progressive visual decline.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Uvea','medium','The most common cause of uveitis in India is:','["Sarcoidosis","Tuberculosis","Herpes simplex","Ankylosing spondylitis"]',1,'Tuberculosis is the most common cause of uveitis in India and other TB-endemic countries. It typically causes posterior uveitis (choroiditis), though any segment can be involved.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Glaucoma','hard','The visual field defect in early glaucoma is:','["Central scotoma","Bjerrum scotoma (arcuate scotoma)","Altitudinal defect","Peripheral constriction"]',1,'Bjerrum scotoma (arcuate scotoma) — an arc-shaped visual field defect following the arcuate nerve fiber layer — is the earliest and most characteristic visual field defect in primary open angle glaucoma.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Retina','hard','Eales disease is characterized by:','["Retinal artery occlusion in elderly","Perivasculitis of retinal veins in young males","Exudative retinopathy","Macular degeneration"]',1,'Eales disease is an idiopathic inflammatory perivasculitis primarily affecting peripheral retinal veins, predominantly in young males from the Indian subcontinent. Causes recurrent vitreous hemorrhage.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Anterior Segment','medium','The best investigation for corneal thickness measurement is:','["Pachymetry","Keratometry","Topography","A-scan ultrasound"]',0,'Pachymetry measures corneal thickness and is essential for glaucoma diagnosis (thin corneas underestimate IOP) and before LASIK surgery to ensure adequate residual corneal thickness.','Kanski Clinical Ophthalmology',2022),

('INICET','Ophthalmology','Neuro-Ophthalmology','hard','Argyll Robertson pupil is characterized by:','["No light reflex, present accommodation","Present light reflex, no accommodation","No light or accommodation reflex","Normal pupil responses"]',0,'Argyll Robertson pupil: small, irregular pupil that accommodates but does not react to light (Light-Near dissociation). Classic finding in neurosyphilis. Due to dorsal midbrain (pretectal) lesion.','Kanski Clinical Ophthalmology',2022);
