INSERT INTO public.question_bank (exam_name, subject, topic, difficulty, text, options, correct, explanation, source, year) VALUES

-- POLITY (52 questions)
('UPSC','Polity','Constitutional Framework','hard','Which Article of the Indian Constitution provides for the Right to Constitutional Remedies?','["Article 14","Article 19","Article 21","Article 32"]',3,'Article 32 is the Right to Constitutional Remedies — the right to move the Supreme Court for enforcement of fundamental rights. Dr. Ambedkar called it the "heart and soul" of the Constitution.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Constitutional Framework','medium','The Preamble of the Indian Constitution was amended by which Constitutional Amendment?','["42nd Amendment, 1976","44th Amendment, 1978","86th Amendment, 2002","73rd Amendment, 1992"]',0,'The 42nd Constitutional Amendment Act (1976) added the words "Socialist," "Secular," and "Integrity" to the Preamble of the Constitution.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Parliament','hard','The concept of "Zero Hour" in the Indian Parliament refers to:','["The first hour of parliamentary session","The time when questions can be asked without prior notice","The period between 12 noon and 1 PM","The time for adjournment motions"]',2,'Zero Hour (12 noon to 1 PM) is an informal device of parliamentary procedure in India. Members raise matters of urgent public importance without prior notice — unique to Indian parliamentary practice.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Constitutional Bodies','medium','The Comptroller and Auditor General of India is related to which Article?','["Article 148","Article 315","Article 124","Article 263"]',0,'Article 148 establishes the Comptroller and Auditor General of India. The CAG audits all expenditures from the Consolidated Fund of India, states, and union territories with legislatures.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Fundamental Rights','hard','The doctrine of "Double Jeopardy" is enshrined in which Article of the Indian Constitution?','["Article 20(1)","Article 20(2)","Article 20(3)","Article 21"]',1,'Article 20(2) — "No person shall be prosecuted and punished for the same offence more than once" — embodies the doctrine of double jeopardy (derived from the 5th Amendment of the US Constitution).','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Federalism','hard','Which schedule of the Indian Constitution deals with the distribution of powers between the Centre and states?','["6th Schedule","7th Schedule","8th Schedule","10th Schedule"]',1,'The 7th Schedule of the Constitution contains three lists: Union List (List I — 97 subjects), State List (List II — 66 subjects), and Concurrent List (List III — 47 subjects).','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Judiciary','medium','The principle of "Judicial Review" in India means:','["The power of courts to review their own judgments","The power to examine constitutionality of laws and executive actions","Annual review of judicial appointments","Review of judicial salaries by Parliament"]',1,'Judicial review is the power of the Supreme Court and High Courts to examine the constitutional validity of laws and executive actions. It flows from Articles 13, 32, and 226.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Local Government','hard','The 73rd Constitutional Amendment related to Panchayati Raj added which Schedule to the Constitution?','["10th Schedule","11th Schedule","12th Schedule","13th Schedule"]',1,'The 73rd Amendment (1992) added the 11th Schedule to the Constitution, listing 29 functional items that may be devolved to panchayats, and Article 243 series for Panchayati Raj institutions.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Constitutional Framework','hard','Which writ is issued to release a person from illegal detention?','["Mandamus","Prohibition","Certiorari","Habeas Corpus"]',3,'Habeas Corpus ("you shall have the body") is a writ issued to produce a person before the court to examine legality of detention. It is a primary safeguard against arbitrary detention.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Parliament','medium','The Speaker of the Lok Sabha is elected by:','["President of India","Members of Lok Sabha","Members of both Houses","Members of Rajya Sabha"]',1,'The Speaker of Lok Sabha is elected by the members of Lok Sabha themselves from among their members. The Speaker is the guardian of the rights and privileges of the House.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Directive Principles','hard','Which Article directs the state to minimize inequalities in income and status?','["Article 39","Article 38","Article 41","Article 44"]',1,'Article 38 directs the state to secure a social order for the promotion of welfare of the people. Article 38(2) specifically directs the state to minimize inequalities in income and status.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Emergency Provisions','hard','Under which Article does the President declare National Emergency?','["Article 352","Article 356","Article 360","Article 365"]',0,'Article 352 empowers the President to proclaim National Emergency when the security of India or any part thereof is threatened by war, external aggression, or armed rebellion.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Constitutional Bodies','medium','The National Human Rights Commission was established under:','["The Human Rights Act, 1993","Article 21 of the Constitution","A Constitutional Amendment","The 44th Amendment Act"]',0,'The NHRC was established under the Protection of Human Rights Act, 1993. The chairman must be a retired Chief Justice of India.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Polity','Fundamental Duties','easy','Fundamental Duties were added to the Constitution by which amendment?','["42nd Amendment","44th Amendment","52nd Amendment","86th Amendment"]',0,'The 42nd Constitutional Amendment Act (1976) added Fundamental Duties (Part IV-A, Article 51A) based on the recommendations of the Swaran Singh Committee (1976).','Indian Polity - M. Laxmikanth',2023),

-- ECONOMY (52 questions)
('UPSC','Economy','Indian Economy','hard','NITI Aayog replaced the Planning Commission in:','["2013","2014","2015","2016"]',2,'NITI Aayog (National Institution for Transforming India) was established on January 1, 2015, replacing the Planning Commission which had been in existence since 1950.','Economic Survey of India',2023),

('UPSC','Economy','Monetary Policy','hard','The Monetary Policy Committee (MPC) was constituted under which Act?','["RBI Act, 1934","FEMA Act, 1999","Banking Regulation Act, 1949","Finance Act, 2016"]',0,'The Monetary Policy Committee (MPC) was constituted under Section 45ZB of the Reserve Bank of India Act, 1934 (as amended in 2016). It has 6 members — 3 RBI officials and 3 government nominees.','Economic Survey of India',2023),

('UPSC','Economy','Fiscal Policy','medium','Fiscal deficit is defined as:','["Revenue deficit + capital expenditure","Total expenditure minus total receipts excluding borrowings","Revenue expenditure minus revenue receipts","Current account deficit"]',1,'Fiscal deficit = Total expenditure - Total receipts excluding borrowings. It indicates the total borrowing requirement of the government and is a key indicator of fiscal health.','Economic Survey of India',2023),

('UPSC','Economy','Banking','hard','The Basel III framework primarily deals with:','["Trade regulations","Capital adequacy and liquidity standards for banks","Insurance sector reform","Foreign exchange management"]',1,'Basel III (Bank for International Settlements) sets minimum capital requirements, leverage ratios, and liquidity coverage ratios for banks to withstand financial stress and prevent banking crises.','Economic Survey of India',2023),

('UPSC','Economy','International Trade','medium','The Merchandise Trade refers to:','["Trade in services only","Trade in physical goods","Both goods and services","Capital account transactions"]',1,'Merchandise trade (visible trade) refers to the import and export of physical/tangible goods. Services trade is called invisible trade. Both together form the current account of the Balance of Payments.','Economic Survey of India',2023),

('UPSC','Economy','Agriculture','hard','The Minimum Support Price (MSP) is fixed by the government based on recommendations of:','["NITI Aayog","Commission for Agricultural Costs and Prices (CACP)","RBI","National Bank for Agriculture (NABARD)"]',1,'MSP is fixed by the Government of India on the recommendations of the Commission for Agricultural Costs and Prices (CACP), taking into account cost of production, demand-supply, and market trends.','Economic Survey of India',2023),

('UPSC','Economy','National Income','medium','GDP at Market Price minus Net Indirect Taxes equals:','["GNP","NNP","GDP at Factor Cost","NDP at Factor Cost"]',2,'GDP at Factor Cost = GDP at Market Price - Net Indirect Taxes (Indirect Taxes - Subsidies). It measures output at the cost of factors of production without the distortion of taxes.','Economic Survey of India',2023),

('UPSC','Economy','Inflation','hard','The Wholesale Price Index (WPI) in India is published by:','["RBI","Ministry of Finance","Office of the Economic Adviser, Ministry of Commerce","CSO"]',2,'WPI is published by the Office of the Economic Adviser (OEA), Ministry of Commerce and Industry on a weekly basis. It measures price changes at the wholesale/producer level.','Economic Survey of India',2023),

('UPSC','Economy','Government Schemes','medium','Pradhan Mantri Jan Dhan Yojana is primarily aimed at:','["Housing for all","Financial inclusion through bank account opening","Agricultural credit","Skill development"]',1,'PMJDY (launched August 28, 2014) aims at financial inclusion by providing universal access to banking facilities with at least one basic bank account per household, RuPay debit card, and accident insurance.','Economic Survey of India',2023),

('UPSC','Economy','International Economics','hard','Special Drawing Rights (SDR) are issued by:','["World Bank","IMF","Asian Development Bank","WTO"]',1,'SDRs are international reserve assets created by the IMF (International Monetary Fund) in 1969. They are allocated to member countries and are based on a basket of five currencies: USD, Euro, CNY, JPY, and GBP.','Economic Survey of India',2023),

('UPSC','Economy','Taxation','medium','GST in India follows which model?','["Origin-based","Destination-based","Hybrid","Production-based"]',1,'GST is a destination-based consumption tax — tax is levied at the place of consumption, not production. Revenue accrues to the state where the goods/services are consumed.','Economic Survey of India',2023),

('UPSC','Economy','Infrastructure','hard','The Insolvency and Bankruptcy Code (IBC) was enacted in:','["2014","2016","2018","2020"]',1,'The Insolvency and Bankruptcy Code, 2016 was enacted to provide a time-bound process (180 days + 90 days extension) for resolving insolvency of companies and individuals.','Economic Survey of India',2023),

-- HISTORY (46 questions)
('UPSC','History','Ancient India','hard','The Indus Valley Civilization belongs to which Bronze Age period?','["5000-4000 BCE","3300-1300 BCE","2000-1000 BCE","1000-500 BCE"]',1,'The Indus Valley Civilization (Harappan Civilization) flourished approximately 3300-1300 BCE (mature phase: 2600-1900 BCE). It was a Bronze Age civilization in the northwestern Indian subcontinent.','Ancient India - R.S. Sharma',2022),

('UPSC','History','Ancient India','medium','The term "Eightfold Path" is associated with:','["Jainism","Hinduism","Buddhism","Ajivika sect"]',2,'The Noble Eightfold Path (Ashtangika Marga) is the path to end suffering in Buddhism: right understanding, right thought, right speech, right action, right livelihood, right effort, right mindfulness, and right concentration.','Ancient India - R.S. Sharma',2022),

('UPSC','History','Medieval India','hard','The Battle of Panipat (First) in 1526 was fought between:','["Akbar and Hemu","Babur and Ibrahim Lodi","Humayun and Sher Shah Suri","Babur and Rana Sanga"]',1,'The First Battle of Panipat (April 21, 1526) was fought between Babur and Ibrahim Lodi (last ruler of Delhi Sultanate). Babur won, establishing the Mughal Empire. He used artillery effectively for the first time in India.','Medieval India - Satish Chandra',2022),

('UPSC','History','Medieval India','medium','The Bhakti movement in South India was pioneered by:','["Kabir","Tukaram","Alvars and Nayanmars","Chaitanya Mahaprabhu"]',2,'The Bhakti movement in South India (6th-9th centuries) was pioneered by the Alvars (Vaishnava poets) and Nayanmars (Shaiva poets). Key figures include Andal, Nammalvar, Appar, and Sundarar.','Medieval India - Satish Chandra',2022),

('UPSC','History','Modern India','hard','The Indian National Congress was founded in 1885 by:','["Bal Gangadhar Tilak","A.O. Hume","Dadabhai Naoroji","Surendranath Banerjee"]',1,'The Indian National Congress was founded on December 28, 1885 by Allan Octavian Hume (a retired British civil servant) at Bombay (Mumbai). W.C. Bonnerjee was the first President.','Modern India - Bipin Chandra',2022),

('UPSC','History','Modern India','hard','The Quit India Movement was launched in:','["1939","1940","1942","1945"]',2,'The Quit India Movement was launched by Mahatma Gandhi on August 8, 1942 at the Bombay session of the All India Congress Committee. The slogan "Do or Die" was given. Nehru, Gandhi were arrested next day.','Modern India - Bipin Chandra',2022),

('UPSC','History','Modern India','medium','The Partition of Bengal (1905) was done by:','["Lord Curzon","Lord Dalhousie","Lord Rippon","Lord Mountbatten"]',0,'Lord Curzon partitioned Bengal on October 16, 1905, dividing it into East Bengal (Muslim-majority, capital Dhaka) and West Bengal (Hindu-majority, capital Calcutta). It sparked the Swadeshi Movement.','Modern India - Bipin Chandra',2022),

('UPSC','History','Ancient India','hard','The Arthashastra, a treatise on statecraft, was written by:','["Ashoka","Chandragupta Maurya","Kautilya (Chanakya)","Megasthenes"]',2,'The Arthashastra was written by Kautilya (also known as Chanakya or Vishnugupta), the prime minister of Chandragupta Maurya. It is a comprehensive treatise on governance, economics, and military strategy.','Ancient India - R.S. Sharma',2022),

('UPSC','History','Freedom Movement','hard','The Chauri Chaura incident (1922) led to:','["Withdrawal of Non-Cooperation Movement","Launch of Civil Disobedience Movement","Formation of Swaraj Party","Jallianwala Bagh massacre"]',0,'The Chauri Chaura incident (February 4, 1922) — where protestors burned a police station killing 22 policemen — led Gandhi to abruptly withdraw the Non-Cooperation Movement, which was controversial among Congress leaders.','Modern India - Bipin Chandra',2022),

('UPSC','History','Modern India','medium','The Simon Commission (1927) was boycotted because:','["It was led by a Conservative","It had no Indian member","It proposed partition","It rejected dominion status"]',1,'The Simon Commission (Indian Statutory Commission, 1927) was boycotted by Indians because it had no Indian member — all seven members were British. It was greeted with "Simon Go Back" protests.','Modern India - Bipin Chandra',2022),

('UPSC','History','Freedom Movement','hard','Gandhi signed the Gandhi-Irwin Pact in 1931 for:','["Round Table Conference participation","Withdrawal of Civil Disobedience Movement","Dominion status demand","Release of all political prisoners"]',0,'The Gandhi-Irwin Pact (March 1931) agreed: Gandhi to attend the 2nd Round Table Conference in London, Congress to suspend Civil Disobedience Movement, government to release political prisoners (not those convicted of violence).','Modern India - Bipin Chandra',2022),

-- GEOGRAPHY (46 questions)
('UPSC','Geography','Physical Geography','hard','The Himalayan rivers are called "Antecedent rivers" because:','["They flow before monsoon","They are older than the Himalayas and cut through them as mountains rose","They flow in opposite direction to wind","They originate in Tibet"]',1,'Antecedent rivers existed before the Himalayas rose. As the mountains rose due to tectonic activity, these rivers (Indus, Ganges, Brahmaputra) maintained their courses by cutting through the rising mountains, forming deep gorges.','NCERT Geography',2023),

('UPSC','Geography','Economic Geography','medium','The Deccan Plateau is made up of:','["Sedimentary rocks","Alluvial soil","Basaltic lava (Deccan Traps)","Granite"]',2,'The Deccan Traps is one of the largest volcanic provinces in the world, formed 66 million years ago during the Cretaceous-Paleogene boundary. It consists of multiple layers of solidified basaltic flood basalt.','NCERT Geography',2023),

('UPSC','Geography','Climatology','hard','The "Masoon" in India is caused by:','["Rotation of Earth","Differential heating of land and sea creating pressure differences","Western disturbances","Jet streams alone"]',1,'The Indian monsoon is caused by differential heating of the Indian subcontinent (land heats up faster) and the Indian Ocean. In summer, low pressure forms over land, drawing moisture-laden winds from the sea.','NCERT Geography',2023),

('UPSC','Geography','Physical Geography','medium','The Sundarbans delta is formed by:','["Brahmaputra and Teesta","Ganges and Brahmaputra","Mahanadi and Godavari","Krishna and Kaveri"]',1,'The Sundarbans is the world largest mangrove forest, formed at the delta of the Ganges and Brahmaputra rivers in the Bay of Bengal, spanning India and Bangladesh.','NCERT Geography',2023),

('UPSC','Geography','Economic Geography','hard','India has the largest deposits of which mineral?','["Iron ore","Coal","Mica","Bauxite"]',2,'India has the world largest reserves of mica and is the leading producer of mica. Jharkhand, Bihar, Rajasthan, and Andhra Pradesh are major producers of mica in India.','NCERT Geography',2023),

('UPSC','Geography','Climatology','medium','The Coriolis force causes:','["Formation of cyclones","Deflection of winds to the right in northern hemisphere","Both A and B","Temperature inversion"]',2,'The Coriolis effect (due to Earth rotation) deflects winds to the right in the Northern Hemisphere and to the left in the Southern Hemisphere. This deflection causes cyclonic circulation around low-pressure systems.','NCERT Geography',2023),

('UPSC','Geography','Physical Geography','hard','The Radcliffe Line is the boundary between:','["India and China","India and Nepal","India and Pakistan","India and Bangladesh"]',2,'The Radcliffe Line is the boundary demarcation line between the Indian and Pakistani portions of Punjab and Bengal provinces of British India, drawn by Sir Cyril Radcliffe in 1947.','NCERT Geography',2023),

('UPSC','Geography','Economic Geography','medium','Project Tiger was launched in which year?','["1968","1970","1973","1980"]',2,'Project Tiger was launched in 1973 under Prime Minister Indira Gandhi to protect tigers and their habitat. The first tiger reserve was established at Jim Corbett National Park, Uttarakhand.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Geography','Physical Geography','hard','The Western Ghats are a UNESCO World Heritage Site because:','["Historical significance","Biodiversity hotspot with endemic species","Mineral wealth","Agricultural importance"]',1,'The Western Ghats (Sahyadri) were declared a UNESCO World Heritage Site in 2012 for their exceptional biodiversity — one of the world eight hottest biodiversity hotspots with numerous endemic species.','NCERT Geography',2023),

('UPSC','Geography','Oceanography','medium','The highest tides in India occur at:','["Mumbai","Kandla","Bhavnagar (Gulf of Khambhat)","Vishakhapatnam"]',2,'The Gulf of Khambhat (Cambay) near Bhavnagar, Gujarat, experiences the highest tides in India (up to 12 metres) due to its funnel shape that amplifies tidal range.','NCERT Geography',2023),

-- SCIENCE & TECHNOLOGY (36 questions)
('UPSC','Science & Technology','Space Technology','hard','ISRO mission that successfully landed on the Moon south pole in 2023:','["Chandrayaan-1","Chandrayaan-2","Chandrayaan-3","Mangalyaan-2"]',2,'Chandrayaan-3 successfully soft-landed its Vikram lander near the lunar south pole on August 23, 2023, making India the first country to achieve a soft landing near the lunar south pole.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Biotechnology','hard','CRISPR-Cas9 is a tool used for:','["DNA sequencing","Gene editing","Protein synthesis","Cell culture"]',1,'CRISPR-Cas9 (Clustered Regularly Interspaced Short Palindromic Repeats) is a revolutionary gene editing tool that allows precise modification of DNA sequences. Jennifer Doudna and Emmanuelle Charpentier won the 2020 Nobel Prize in Chemistry for this.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Nuclear Technology','medium','India tested its nuclear device for the first time in:','["1971","1974","1978","1980"]',1,'India conducted its first nuclear test at Pokhran, Rajasthan on May 18, 1974, codenamed "Smiling Buddha." The second series of tests (Pokhran-II, Operation Shakti) was conducted in May 1998.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Defence','hard','The Agni-V missile is classified as:','["Short-range ballistic missile","Intermediate range ballistic missile","Intercontinental ballistic missile (ICBM)","Anti-ship missile"]',2,'Agni-V is an Intercontinental Ballistic Missile (ICBM) with a range of over 5,000 km (some estimates up to 8,000 km), capable of carrying nuclear warheads. It was first tested in April 2012.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Information Technology','medium','India Stack refers to:','["Software stack for startups","Digital public infrastructure including Aadhaar, UPI, DigiLocker","Cloud computing infrastructure","Cybersecurity framework"]',1,'India Stack is a set of open APIs and digital public goods that enable governments, businesses, and developers to utilize a unique digital infrastructure — includes Aadhaar authentication, UPI payments, DigiLocker, and Consent layer.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Space Technology','medium','The UPI (Unified Payments Interface) was launched by:','["Ministry of Finance","National Payments Corporation of India (NPCI)","RBI directly","State Bank of India"]',1,'UPI was developed and launched by NPCI (National Payments Corporation of India) in 2016. It enables instant real-time payment between bank accounts using mobile phones.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Emerging Technology','hard','Which country launched the first quantum communication satellite?','["USA","Russia","China","India"]',2,'China launched the world first quantum communication satellite, Micius (Mozi), in August 2016. It demonstrated quantum key distribution between satellite and ground stations over distances of 1,200 km.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Biotechnology','medium','The term "mRNA vaccine" became prominent during:','["Ebola epidemic","Zika outbreak","COVID-19 pandemic","H1N1 influenza"]',2,'mRNA vaccines (Pfizer-BioNTech and Moderna) were developed during the COVID-19 pandemic. They use messenger RNA to instruct cells to produce a protein that triggers an immune response, without using live virus.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Space Technology','hard','India first Mars mission (Mangalyaan) was launched in:','["2012","2013","2014","2015"]',1,'Mangalyaan (Mars Orbiter Mission) was launched on November 5, 2013 by ISRO and successfully entered Mars orbit on September 24, 2014. India became the first country to reach Mars on its first attempt.','Science & Technology for UPSC',2023),

('UPSC','Science & Technology','Environment','medium','The Montreal Protocol deals with:','["Climate change (CO2 emissions)","Ozone depleting substances","Marine pollution","Biodiversity conservation"]',1,'The Montreal Protocol (1987) is a landmark international treaty designed to protect the ozone layer by phasing out ozone depleting substances (ODS) like CFCs, HCFCs, and halons.','Environment for UPSC - Shankar IAS',2023),

-- ENVIRONMENT & ECOLOGY (36 questions)
('UPSC','Environment','Climate Change','hard','The Paris Agreement aims to limit global temperature rise to:','["1°C above pre-industrial levels","1.5°C-2°C above pre-industrial levels","2.5°C above pre-industrial levels","3°C above pre-industrial levels"]',1,'The Paris Agreement (COP21, 2015) aims to limit global average temperature rise to well below 2°C above pre-industrial levels, with efforts to limit the increase to 1.5°C, to reduce climate change impacts.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Biodiversity','hard','Which of the following is a biodiversity hotspot in India?','["Indo-Gangetic plains","Thar desert","Western Ghats","Deccan Plateau"]',2,'The Western Ghats (and Sri Lanka) and the Himalaya are the two biodiversity hotspots in India (as designated by Conservation International). Hotspots must have 1,500+ endemic vascular plants and have lost 70%+ of original habitat.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','International Agreements','medium','The Ramsar Convention deals with:','["Endangered species","Wetlands of international importance","Marine pollution","Desertification"]',1,'The Ramsar Convention on Wetlands (1971) is an international treaty for the conservation and sustainable use of wetlands. India has the highest number of Ramsar sites in South Asia.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Pollution','hard','PM 2.5 refers to particulate matter with diameter:','["Less than 25 microns","Less than 2.5 microns","Between 2.5-10 microns","Greater than 10 microns"]',1,'PM2.5 refers to fine particulate matter with aerodynamic diameter less than 2.5 micrometers. These particles can penetrate deep into the lungs and enter the bloodstream, causing serious health effects.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Climate Change','medium','Carbon credits were introduced by which agreement?','["Paris Agreement (2015)","Kyoto Protocol (1997)","Rio Earth Summit (1992)","Montreal Protocol (1987)"]',1,'Carbon credits/carbon trading was introduced by the Kyoto Protocol (1997). Under the Clean Development Mechanism (CDM), developed countries can earn carbon credits by financing emission-reduction projects in developing countries.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Ecology','hard','Which of the following is an in-situ conservation method?','["Seed bank","Botanical garden","National Park","Zoo"]',2,'In-situ conservation conserves species in their natural habitat. National Parks, Wildlife Sanctuaries, and Biosphere Reserves are in-situ methods. Zoos, botanical gardens, and seed banks are ex-situ methods.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Pollution','medium','The term "Eutrophication" refers to:','["Soil erosion","Excessive growth of algae due to nutrient enrichment of water bodies","Air pollution from vehicles","Noise pollution in cities"]',1,'Eutrophication is the process by which water bodies become enriched in dissolved nutrients (nitrates, phosphates from agricultural runoff), promoting excessive plant/algae growth, depleting oxygen, and causing dead zones.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Biodiversity','medium','The IUCN Red List criteria classify species as Critically Endangered when:','["Population reduced by 50% in 10 years","Population reduced by 80% in 10 years or 3 generations","Population below 2500 mature individuals","All of the above"]',3,'IUCN CR criteria: population reduction > 80% in 10 years/3 generations, restricted range (area < 100 km2), population < 250 mature individuals, quantitative analysis showing >50% extinction probability in 10 years. Any one criterion qualifies.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Climate Change','hard','The concept of "Blue Carbon" refers to:','["Carbon stored in ocean water","Carbon stored in coastal and marine ecosystems (mangroves, seagrasses, salt marshes)","Carbon credits traded internationally","Carbon captured by algae farms"]',1,'Blue carbon is carbon captured and stored by coastal and marine ecosystems — mangroves, seagrasses, and salt marshes. These ecosystems store carbon at rates 3-5 times greater than tropical forests.','Environment for UPSC - Shankar IAS',2023),

('UPSC','Environment','Ecology','medium','Which of the following best describes a "Biosphere Reserve"?','["A strict nature reserve with no human habitation","A protected area with multiple zones including core, buffer, and transition zones","A marine protected area","A botanical garden"]',1,'Biosphere Reserves have a three-zone system: core zone (strictly protected, no human activity), buffer zone (limited research/tourism), and transition zone (human habitation and sustainable use allowed).','Environment for UPSC - Shankar IAS',2023),

-- CURRENT AFFAIRS / GOVERNANCE (36 questions)
('UPSC','Governance','Indian Governance','medium','The Right to Information (RTI) Act was enacted in:','["2003","2005","2007","2009"]',1,'The Right to Information Act was enacted in 2005, giving citizens the right to request information from public authorities. It replaced the Freedom of Information Act 2002.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Governance','Indian Governance','hard','Which constitutional body regulates elections in India?','["Election Commission of India","Parliament","Ministry of Law","Supreme Court"]',0,'The Election Commission of India is an autonomous constitutional body (Article 324) responsible for superintendence, direction, and control of elections to Parliament, State Legislatures, and offices of President and Vice-President.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Governance','International Relations','medium','The BRICS grouping comprises:','["Brazil, Russia, India, China, Saudi Arabia","Brazil, Russia, India, China, South Africa","Brazil, Russia, Indonesia, China, South Africa","Bolivia, Russia, India, China, South Africa"]',1,'BRICS originally comprised Brazil, Russia, India, China, and South Africa. In 2024, the group expanded to include Egypt, Ethiopia, Iran, UAE, and Saudi Arabia (with full membership from January 2024).','Current Affairs 2023',2023),

('UPSC','Governance','Indian Governance','hard','The three-language formula in India recommends:','["Hindi, English, and Sanskrit","Regional language, Hindi, and English","Any three Indian languages","Hindi, English, and a foreign language"]',1,'The Three-Language Formula recommends that students study: their regional/mother tongue language, Hindi (or another Indian language in Hindi-speaking states), and English.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Governance','International Relations','hard','The Quad (Quadrilateral Security Dialogue) consists of:','["USA, UK, Australia, Canada","USA, Japan, India, Australia","USA, Japan, South Korea, Australia","USA, UK, India, Japan"]',1,'The Quad (Quadrilateral Security Dialogue) is a strategic security dialogue between the United States, India, Australia, and Japan, discussing security, economic, and technological issues in the Indo-Pacific.','Current Affairs 2023',2023),

('UPSC','Governance','Indian Governance','medium','The MGNREGS (Mahatma Gandhi National Rural Employment Guarantee Scheme) guarantees:','["100 days of employment per family per year","200 days of employment per adult per year","100 days of employment per adult per year","150 days of employment per family per year"]',0,'MGNREGS guarantees 100 days of wage employment per financial year to every rural household whose adult members volunteer to do unskilled manual work. Extended to 150 days in drought-affected areas.','Government Schemes for UPSC',2023),

('UPSC','Governance','International Organizations','hard','The International Court of Justice (ICJ) is located in:','["New York","Geneva","The Hague","Brussels"]',2,'The International Court of Justice (ICJ) is the principal judicial organ of the United Nations, located at the Peace Palace in The Hague, Netherlands. It settles disputes between nations and gives advisory opinions.','International Relations for UPSC',2023),

('UPSC','Governance','Indian Governance','hard','Which article of the Constitution deals with Uniform Civil Code?','["Article 40","Article 44","Article 51","Article 48"]',1,'Article 44 of the Constitution (Directive Principle of State Policy) directs the state to endeavour to secure for citizens a Uniform Civil Code throughout the territory of India.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Governance','International Organizations','medium','The World Trade Organization (WTO) was established in:','["1948","1990","1995","2000"]',2,'The WTO was established on January 1, 1995, replacing the General Agreement on Tariffs and Trade (GATT, 1948). It is the international organization dealing with rules of trade between nations.','International Relations for UPSC',2023),

('UPSC','Governance','Indian Governance','hard','The 101st Constitutional Amendment Act (2016) is related to:','["Lokpal","GST (Goods and Services Tax)","Right to Education","Anti-defection law"]',1,'The 101st Constitutional Amendment Act, 2016 introduced the Goods and Services Tax (GST) in India. It amended Articles 246A, 269A, and 279A and inserted them into the Constitution.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Governance','Indian Governance','medium','The National Food Security Act (2013) covers what percentage of population?','["50%","67%","75%","80%"]',1,'The National Food Security Act (2013) covers up to 75% of rural and 50% of urban population (approximately 67% of total population) for subsidized food grains under the Targeted Public Distribution System.','Government Schemes for UPSC',2023),

('UPSC','Governance','International Relations','hard','ASEAN (Association of Southeast Asian Nations) has its headquarters in:','["Bangkok","Singapore","Jakarta","Kuala Lumpur"]',2,'ASEAN Secretariat is located in Jakarta, Indonesia. ASEAN was founded on August 8, 1967 in Bangkok (Bangkok Declaration) with 5 founding members; it now has 10 member states.','International Relations for UPSC',2023),

('UPSC','Governance','Ethics','hard','The term "Conflict of Interest" in public service refers to:','["Disagreement between departments","Situation where personal interests may improperly influence official duties","War between nations","Labor dispute"]',1,'Conflict of interest occurs when an official relationship (personal gain, outside employment, family interest) might unduly influence the exercise of official duties. It is a key concept in public service ethics and integrity.','Ethics, Integrity, and Aptitude for UPSC',2023),

('UPSC','Governance','Ethics','medium','The concept of "Emotional Intelligence" was popularized by:','["Abraham Maslow","Daniel Goleman","Peter Drucker","Howard Gardner"]',1,'Daniel Goleman popularized Emotional Intelligence (EQ) through his 1995 book. EQ includes self-awareness, self-regulation, empathy, motivation, and social skills — increasingly important for civil service leadership.','Ethics, Integrity, and Aptitude for UPSC',2023),

('UPSC','Governance','Indian Governance','hard','The Lokpal Act was passed in:','["2011","2013","2014","2016"]',1,'The Lokpal and Lokayuktas Act was passed by Parliament in 2013, providing for the establishment of Lokpal at the Centre and Lokayuktas in states to inquire into allegations of corruption against public functionaries.','Indian Polity - M. Laxmikanth',2023),

('UPSC','Governance','International Relations','medium','India signed the Indo-US Civil Nuclear Agreement in:','["2005","2006","2008","2010"]',2,'The Indo-US Civil Nuclear Agreement (123 Agreement) was operationalized in 2008, allowing India to access civilian nuclear technology and fuel from the US despite not being a signatory to the NPT.','International Relations for UPSC',2023);
