INSERT INTO public.question_bank (exam_name, subject, topic, difficulty, text, options, correct, explanation, source, year) VALUES

-- DATA STRUCTURES (46 questions)
('GATE','Data Structures','Arrays & Sorting','medium','What is the time complexity of the best-case scenario for Bubble Sort?','["O(n²)","O(n log n)","O(n)","O(log n)"]',2,'With the optimized version (early termination when no swaps occur), Bubble Sort achieves O(n) in the best case when the array is already sorted.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Arrays & Sorting','hard','What is the worst-case time complexity of QuickSort?','["O(n log n)","O(n²)","O(n)","O(n³)"]',1,'QuickSort worst case O(n²) occurs when the pivot is always the smallest or largest element (e.g., sorted array with first/last element as pivot). Average case is O(n log n).','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Linked Lists','medium','In a doubly linked list, what is the time complexity of deleting a node given a pointer to it?','["O(n)","O(log n)","O(1)","O(n²)"]',2,'With a pointer to the node and access to both prev and next pointers, deletion requires only O(1) pointer adjustments — no traversal needed.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Trees','hard','The number of distinct binary trees with n nodes is given by the nth Catalan number. For n=3, how many distinct binary trees exist?','["3","4","5","6"]',2,'The nth Catalan number Cn = C(2n,n)/(n+1). For n=3: C3 = C(6,3)/4 = 20/4 = 5. Five distinct binary trees can be formed with 3 nodes.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Trees','hard','In an AVL tree, what is the maximum height difference allowed between left and right subtrees?','["0","1","2","3"]',1,'An AVL tree (Adelson-Velsky and Landis tree) maintains the height balance property: the heights of left and right subtrees of any node differ by at most 1 (balance factor ∈ {-1, 0, 1}).','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Stacks & Queues','medium','A stack is used to evaluate postfix expression "2 3 4 * +". The result is:','["14","20","17","25"]',0,'Process: push 2, push 3, push 4. See *: pop 4 and 3, push 3*4=12. See +: pop 12 and 2, push 2+12=14. Result = 14.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Heaps','hard','In a max-heap with n elements, what is the time complexity to extract the maximum element?','["O(1)","O(log n)","O(n)","O(n log n)"]',1,'Extracting the maximum (root) requires: remove root O(1), replace with last element O(1), then heapify-down O(log n). Total: O(log n).','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Graphs','medium','The time complexity of Breadth-First Search (BFS) on a graph with V vertices and E edges is:','["O(V)","O(E)","O(V + E)","O(V × E)"]',2,'BFS visits each vertex once and each edge once. Time complexity is O(V + E) — linear in the size of the graph (vertices + edges).','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Hashing','hard','Which collision resolution technique in hashing uses a linked list at each bucket?','["Open addressing","Separate chaining","Linear probing","Quadratic probing"]',1,'Separate chaining (closed addressing) handles collisions by maintaining a linked list at each hash table slot. Open addressing (linear/quadratic probing) finds alternative slots within the table.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Trees','medium','Which traversal of a Binary Search Tree (BST) gives elements in sorted order?','["Preorder","Postorder","Inorder","Level-order"]',2,'Inorder traversal (left → root → right) of a BST visits nodes in ascending sorted order. This property is fundamental to BST operations.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Arrays & Sorting','hard','What is the time complexity of merge sort in all cases?','["O(n)","O(n log n)","O(n²)","O(log n)"]',1,'Merge Sort has O(n log n) time complexity in all cases (best, average, worst). It divides the array in O(log n) levels and merges in O(n) at each level.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Graphs','hard','Dijkstra algorithm fails when:','["Graph has cycles","Graph has negative weight edges","Graph is undirected","Graph is sparse"]',1,'Dijkstra algorithm assumes non-negative edge weights. With negative edges, the greedy approach fails as a shorter path might be found through a node already finalized. Use Bellman-Ford for negative weights.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Trees','hard','A complete binary tree with 15 nodes has height:','["3","4","5","2"]',0,'Height of complete binary tree with n nodes = floor(log₂n). floor(log₂15) = 3 (since 2³=8 ≤ 15 < 16=2⁴). Height = 3.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Stacks & Queues','hard','Which data structure is used in implementing Depth-First Search (DFS)?','["Queue","Stack","Priority Queue","Deque"]',1,'DFS uses a Stack (or recursion, which uses the call stack). LIFO order ensures depth-first exploration. BFS uses a Queue (FIFO) for level-by-level exploration.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Arrays & Sorting','hard','Heapsort has which of the following properties?','["Stable, in-place","Not stable, in-place","Stable, not in-place","Not stable, not in-place"]',1,'Heapsort is in-place (O(1) extra space) but NOT stable — equal elements may be reordered because the heap property does not maintain relative order of equal elements.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Graphs','hard','In Kruskal algorithm for Minimum Spanning Tree, the edges are processed in:','["Decreasing order of weight","Increasing order of weight","Random order","BFS order"]',1,'Kruskal algorithm sorts all edges in increasing order of weight and greedily adds the cheapest edge that does not form a cycle, using Union-Find data structure to detect cycles.','GATE Computer Science - Arihant',2023),

('GATE','Data Structures','Hashing','medium','If a hash table has load factor α, the expected number of comparisons for unsuccessful search with chaining is:','["1 + α/2","α","1 + α","α/2"]',2,'With separate chaining, expected number of comparisons for unsuccessful search = 1 + α (one comparison to check the chain head, plus α comparisons on average to traverse the chain).','GATE Computer Science - Arihant',2023),

-- ALGORITHMS (44 questions)
('GATE','Algorithms','Dynamic Programming','hard','The time complexity of the standard dynamic programming solution to the 0/1 Knapsack problem with n items and capacity W is:','["O(n + W)","O(n × W)","O(n²)","O(2^n)"]',1,'The 0/1 Knapsack DP solution fills an n×W table, with each cell computed in O(1). Total time = O(n × W). The brute-force approach is O(2^n).','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Greedy','hard','Which of the following problems CANNOT be solved optimally by a greedy algorithm?','["Huffman coding","Activity selection","0/1 Knapsack","Fractional Knapsack"]',2,'The 0/1 Knapsack problem cannot be solved optimally by greedy — items cannot be fractioned, so greedy by value/weight ratio may miss optimal combinations. Fractional Knapsack IS solvable greedily.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Divide & Conquer','medium','The recurrence T(n) = 2T(n/2) + O(n) solves to:','["O(n)","O(n log n)","O(n²)","O(log n)"]',1,'By Master Theorem Case 2: a=2, b=2, f(n)=n=n^(log_b a)=n^1. Since f(n) = Θ(n^log_b a), T(n) = O(n log n). This is the recurrence for Merge Sort.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Graph Algorithms','hard','Floyd-Warshall algorithm finds:','["Single source shortest path","All pairs shortest path","Minimum spanning tree","Longest path"]',1,'Floyd-Warshall finds all-pairs shortest paths in O(V³) time and O(V²) space. It works with negative edge weights but not negative cycles. Uses dynamic programming.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Complexity','hard','Which complexity class contains problems solvable in polynomial time?','["NP","P","NP-Complete","NP-Hard"]',1,'Class P (Polynomial time) contains problems solvable by a deterministic Turing machine in polynomial time. NP contains problems verifiable in polynomial time. P ⊆ NP (whether P = NP is unsolved).','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Dynamic Programming','hard','The Longest Common Subsequence (LCS) of "ABCBDAB" and "BDCAB" has length:','["3","4","5","6"]',1,'LCS of ABCBDAB and BDCAB: the LCS is "BCAB" or "BDAB" with length 4.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Sorting','medium','Which sorting algorithm is the most efficient for nearly sorted arrays?','["QuickSort","HeapSort","Insertion Sort","Selection Sort"]','[0,1,2,3]',2,'Insertion Sort performs O(n) comparisons on a nearly sorted array (each element is close to its final position). QuickSort degrades to O(n²) for sorted arrays with naive pivot selection.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Complexity','hard','The problem of determining whether a Boolean formula is satisfiable is known as:','["P problem","NP-Complete (SAT)","NP-Hard but not NP-Complete","Undecidable"]',1,'SAT (Boolean Satisfiability Problem) was the first problem proven to be NP-Complete (Cook-Levin theorem, 1971). It is the canonical NP-Complete problem.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Graph Algorithms','medium','Topological sort can be applied to:','["Undirected graphs","Directed Acyclic Graphs (DAG)","Graphs with cycles","Complete graphs"]',1,'Topological sort is defined only for Directed Acyclic Graphs (DAGs). It produces a linear ordering of vertices such that for every edge u→v, u comes before v.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Divide & Conquer','hard','The recurrence T(n) = T(n/2) + O(1) (as in Binary Search) solves to:','["O(1)","O(n)","O(log n)","O(n log n)"]',2,'Master Theorem Case 2 does not apply here. T(n/2)+1: a=1, b=2, f(n)=1=n^0=n^(log_2 1). Case 2: T(n)=O(log n). Binary Search is O(log n).','GATE Computer Science - Arihant',2023),

-- OPERATING SYSTEMS (44 questions)
('GATE','Operating Systems','Process Management','hard','Which scheduling algorithm minimizes average waiting time?','["FCFS","Round Robin","Shortest Job First (SJF)","Priority Scheduling"]',2,'Shortest Job First (SJF) / Shortest Job Next is provably optimal for minimizing average waiting time among non-preemptive scheduling algorithms. Preemptive version (SRTF) is optimal overall.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Memory Management','hard','Page replacement algorithm with minimum page faults is:','["FIFO","LRU","Optimal (Belady)","Clock"]',2,'Belady Optimal Algorithm replaces the page that will not be used for the longest time in future. It gives minimum page faults but is not implementable in practice (requires future knowledge).','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Synchronization','hard','The critical section problem requires:','["Mutual exclusion only","Mutual exclusion, progress, and bounded waiting","Deadlock prevention","Semaphore implementation"]',1,'Critical section requirements: (1) Mutual Exclusion — only one process in CS at a time; (2) Progress — if no process is in CS, a waiting process can enter; (3) Bounded Waiting — limit on how long a process waits.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Deadlock','medium','Which condition is NOT required for deadlock?','["Mutual exclusion","Hold and wait","No preemption","Starvation"]',3,'Coffman conditions for deadlock: (1) Mutual exclusion, (2) Hold and wait, (3) No preemption, (4) Circular wait. Starvation is a separate problem (indefinite postponement) and is NOT a necessary condition for deadlock.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Memory Management','hard','In demand paging, the page table entry has a valid/invalid bit. A page fault occurs when:','["The process accesses RAM","The valid bit is 0 (page not in memory)","The page is in swap space","The TLB has a miss"]',1,'A page fault occurs when a process tries to access a page whose valid bit is 0 — meaning the page is not currently in physical memory (it may be on disk). The OS must then bring the page into memory.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','File Systems','medium','The inode in UNIX file system stores:','["File name","File data","File metadata (permissions, size, timestamps, block pointers)","Directory structure"]',2,'An inode (index node) stores file metadata: file type, permissions, owner, size, timestamps, and block pointers (direct, single/double/triple indirect). The file name is stored in the directory, not the inode.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Process Management','hard','Context switching overhead is associated with:','["Saving and restoring process state (PCB)","Memory allocation","Disk I/O","Network communication"]',0,'Context switching involves saving the current process state (registers, PC, stack pointer) to its PCB and restoring the new process state. This overhead reduces effective CPU utilization.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Synchronization','hard','The dining philosophers problem illustrates:','["Memory management","Deadlock and synchronization among competing processes","CPU scheduling","Virtual memory"]',1,'The Dining Philosophers problem (Dijkstra) illustrates challenges in concurrent programming — specifically deadlock (all philosophers hold one chopstick and wait for another) and synchronization.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Memory Management','medium','Thrashing occurs when:','["CPU utilization is 100%","Processes spend more time paging than executing","Memory is completely free","Disk I/O is minimal"]',1,'Thrashing occurs when the OS spends more time swapping pages in and out of memory than executing processes. Caused by insufficient frames allocated to processes, leading to excessive page faults.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Deadlock','hard','Banker algorithm is used for:','["Deadlock detection","Deadlock prevention","Deadlock avoidance","Deadlock recovery"]',2,'Banker algorithm (Dijkstra) is a deadlock avoidance algorithm. It checks if resource allocation would leave the system in a safe state before granting requests, ensuring deadlock never occurs.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Process Management','medium','A zombie process is:','["A process waiting for I/O","A process that has finished execution but its entry is still in the process table","A process in ready state","A suspended process"]',1,'A zombie process has completed execution but its process table entry remains because the parent has not yet called wait() to read the exit status. It occupies minimal resources but uses a process table slot.','Operating Systems - Galvin',2023),

('GATE','Operating Systems','Memory Management','hard','Which page replacement algorithm suffers from Belady anomaly?','["LRU","Optimal","FIFO","LFU"]',2,'Belady anomaly: increasing the number of frames can increase page faults with FIFO. LRU and Optimal are stack algorithms — they are immune to Belady anomaly.','Operating Systems - Galvin',2023),

-- DATABASE MANAGEMENT SYSTEMS (44 questions)
('GATE','DBMS','Relational Algebra','hard','Which SQL operation corresponds to relational algebra JOIN?','["UNION","SELECT","NATURAL JOIN","PROJECT"]',2,'Natural Join in relational algebra combines tuples from two relations that have equal values in common attributes (corresponding to SQL NATURAL JOIN). SELECT corresponds to σ (selection), PROJECT to π.','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Normalization','hard','A relation is in BCNF if for every non-trivial functional dependency X→Y, X is:','["A candidate key","A superkey","A prime attribute","A foreign key"]',1,'Boyce-Codd Normal Form (BCNF): for every non-trivial functional dependency X→Y in a relation, X must be a superkey. BCNF is stronger than 3NF.','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','SQL','medium','The SQL command to remove all rows from a table without deleting the table structure is:','["DROP TABLE","DELETE FROM table","TRUNCATE TABLE","ALTER TABLE"]',2,'TRUNCATE TABLE removes all rows from a table efficiently (cannot be rolled back in most DBMS, unlike DELETE). DROP TABLE removes the table structure entirely. DELETE FROM allows WHERE clause filtering.','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Indexing','hard','A B+ tree index on a relation with n records at level h has search complexity:','["O(n)","O(log n)","O(h) = O(log_d n) where d is degree","O(1)"]',2,'B+ tree search: navigate from root to leaf through h levels where h = O(log_d n) and d is the degree (branching factor). Each level requires one disk I/O, so search is O(log n).','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Transactions','hard','ACID properties in database transactions stand for:','["Atomicity, Consistency, Isolation, Durability","Accuracy, Concurrency, Integrity, Distribution","Atomicity, Concurrency, Isolation, Data integrity","Accuracy, Consistency, Integration, Durability"]',0,'ACID: Atomicity (all or nothing), Consistency (valid state to valid state), Isolation (concurrent transactions appear serial), Durability (committed changes persist despite failures).','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','SQL','hard','Find the error in: SELECT dept, AVG(salary) FROM employee GROUP BY dept HAVING salary > 50000','["No error","HAVING clause should use aggregate: HAVING AVG(salary) > 50000","GROUP BY should come after HAVING","AVG should be SUM"]',1,'HAVING clause filters groups (after GROUP BY). Individual column references like "salary" are not valid in HAVING — you must use an aggregate function: HAVING AVG(salary) > 50000.','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Normalization','medium','Which normal form deals with multi-valued dependencies?','["2NF","3NF","BCNF","4NF"]',3,'4NF (Fourth Normal Form) deals with multi-valued dependencies. A relation is in 4NF if it is in BCNF and has no non-trivial multi-valued dependencies (where one attribute determines a set of values of another).','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Transactions','hard','Two-Phase Locking (2PL) guarantees:','["Deadlock freedom","Serializability","Both serializability and deadlock freedom","High throughput"]',1,'2PL guarantees conflict serializability — the schedule is equivalent to some serial schedule. However, 2PL does NOT prevent deadlocks (two transactions can each hold a lock the other needs).','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','SQL','medium','Which of the following is a DDL (Data Definition Language) command?','["INSERT","UPDATE","CREATE TABLE","SELECT"]',2,'DDL commands define database structure: CREATE, ALTER, DROP, TRUNCATE. DML (Data Manipulation Language) commands manipulate data: SELECT, INSERT, UPDATE, DELETE.','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Relational Algebra','hard','The operation that selects specific columns from a relation is:','["Selection (σ)","Projection (π)","Join (⋈)","Union (∪)"]',1,'Projection (π) in relational algebra selects specific attributes (columns) from a relation, eliminating duplicate tuples. Selection (σ) filters rows based on a condition.','Database System Concepts - Silberschatz',2023),

('GATE','DBMS','Normalization','hard','If a relation has only one candidate key, it is always in:','["1NF","2NF","3NF","BCNF"]',3,'If a relation has exactly one candidate key, every non-trivial FD X→Y must have X as a superkey (since the only candidate key is a superkey). This satisfies BCNF automatically.','Database System Concepts - Silberschatz',2023),

-- COMPUTER NETWORKS (44 questions)
('GATE','Computer Networks','Network Layer','hard','Which routing protocol uses the Bellman-Ford algorithm?','["OSPF","RIP","BGP","EIGRP"]',1,'RIP (Routing Information Protocol) uses the Bellman-Ford distance vector algorithm. OSPF uses Dijkstra link-state algorithm. BGP is a path vector protocol.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Transport Layer','hard','TCP uses which mechanism to ensure reliable data transfer?','["Stop-and-wait","Acknowledgements, sequence numbers, and retransmission","Checksum only","Flow control only"]',1,'TCP reliability: sequence numbers (detect out-of-order), acknowledgements (confirm receipt), retransmission (on timeout/triple duplicate ACK), flow control (receiver window), and congestion control.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Application Layer','medium','The DNS (Domain Name System) translates:','["IP to MAC address","Domain names to IP addresses","URLs to domain names","Port numbers to services"]',1,'DNS translates human-readable domain names (e.g., google.com) to IP addresses (e.g., 142.250.195.78). It is a hierarchical distributed database system (root → TLD → authoritative servers).','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Data Link Layer','hard','CRC (Cyclic Redundancy Check) is used for:','["Encryption","Error detection","Flow control","Routing"]',1,'CRC is an error-detecting code based on polynomial division. The sender appends a CRC checksum; the receiver verifies it. CRC can detect all burst errors shorter than the degree of the generator polynomial.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Network Layer','hard','The number of usable host addresses in a /28 subnet is:','["14","16","30","32"]',0,'A /28 subnet has 32-28=4 host bits. Total addresses = 2^4=16. Usable hosts = 16-2=14 (subtract network address and broadcast address).','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Transport Layer','medium','Which port does HTTP use by default?','["21","23","80","443"]',2,'HTTP uses port 80 by default. HTTPS uses port 443. FTP uses port 21. SSH uses port 22. Telnet uses port 23.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Network Layer','medium','NAT (Network Address Translation) is used to:','["Translate MAC to IP","Allow multiple private IP devices to share a public IP","Encrypt network traffic","Filter packets"]',1,'NAT translates private IP addresses to a public IP address (and vice versa), allowing multiple devices in a private network to share a single public IP. It also provides a degree of security by hiding internal addresses.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Application Layer','hard','Which protocol provides secure web communication?','["HTTP","FTP","HTTPS (HTTP over TLS/SSL)","SMTP"]',2,'HTTPS (HTTP Secure) uses TLS (Transport Layer Security) or its predecessor SSL to encrypt HTTP communications, providing authentication, data integrity, and confidentiality.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Data Link Layer','medium','The MAC address is used at which OSI layer?','["Network layer","Data Link layer","Transport layer","Physical layer"]',1,'MAC (Media Access Control) address is a Layer 2 (Data Link layer) address, used for communication within a local network segment. IP addresses operate at Layer 3 (Network layer).','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Transport Layer','hard','TCP three-way handshake sequence is:','["SYN → SYN-ACK → ACK","ACK → SYN → SYN-ACK","SYN → ACK → SYN-ACK","FIN → FIN-ACK → ACK"]',0,'TCP connection establishment: Client sends SYN, Server responds with SYN-ACK, Client sends ACK. This three-way handshake establishes synchronized sequence numbers for reliable communication.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Network Layer','hard','OSPF (Open Shortest Path First) uses which algorithm?','["Bellman-Ford","Dijkstra shortest path algorithm","Floyd-Warshall","Prim algorithm"]',1,'OSPF is a link-state routing protocol that uses Dijkstra Shortest Path First algorithm. Each router maintains a complete topology map and computes shortest paths independently.','Computer Networks - Tanenbaum',2023),

('GATE','Computer Networks','Physical Layer','medium','Nyquist theorem states that the maximum data rate for a noiseless channel with bandwidth B Hz is:','["B log₂M bps","2B log₂M bps","B/2 log₂M bps","4B log₂M bps"]',1,'Nyquist theorem: Max data rate = 2B log₂M, where B is bandwidth in Hz and M is the number of discrete signal levels. Shannon theorem adds noise: C = B log₂(1 + S/N).','Computer Networks - Tanenbaum',2023),

-- THEORY OF COMPUTATION (36 questions)
('GATE','Theory of Computation','Automata','hard','Which of the following languages is NOT regular?','["All strings over {a,b} ending in ab","Strings with equal number of 0s and 1s","All strings over {a} with even length","Language of binary numbers divisible by 3"]',1,'Strings with equal number of 0s and 1s require counting (memory proportional to input length), which finite automata cannot do. By the pumping lemma, this language is not regular.','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Automata','medium','The minimum number of states in DFA accepting strings over {a,b} that end in "ab" is:','["2","3","4","5"]',1,'States needed: q0 (start/others), q1 (last char was a), q2 (last two chars were ab, accept). Minimum 3 states.','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Context-Free Languages','hard','The language {a^n b^n | n ≥ 1} is:','["Regular","Context-Free but not Regular","Context-Sensitive but not CF","Recursively Enumerable"]',1,'L = {a^n b^n} is the canonical context-free language — accepted by a pushdown automaton but not by any finite automaton (provable by pumping lemma for regular languages).','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Turing Machines','hard','The Halting Problem is:','["Decidable","Semi-decidable (recognizable)","Not recognizable","Solvable in polynomial time"]',1,'The Halting Problem (does a Turing machine M halt on input w?) is undecidable (proven by Turing, 1936). It is semi-decidable (recursively enumerable): if M halts, we can verify it, but we cannot verify non-halting.','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Automata','hard','ε-NFA differs from NFA in that:','["ε-NFA cannot accept empty strings","ε-NFA has transitions on empty string (ε)","ε-NFA is more powerful than NFA","ε-NFA cannot be converted to DFA"]',1,'ε-NFA (Non-deterministic Finite Automaton with epsilon transitions) allows transitions on the empty string ε without consuming input. Every ε-NFA can be converted to an equivalent DFA (all three models are equivalent).','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Pumping Lemma','hard','The pumping lemma for regular languages states that for any regular language L, there exists p (pumping length) such that any string w in L with |w| ≥ p can be written as w=xyz where:','["y can be pumped (xy^iz is in L for i≥0)","x must be empty","z must be empty","|y|=1"]',0,'Pumping Lemma: w=xyz where |xy|≤p, |y|≥1, and for all i≥0, xy^iz ∈ L. Used to prove languages are NOT regular by showing any such decomposition violates the condition.','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Context-Free Languages','medium','A Pushdown Automaton (PDA) accepts context-free languages using:','["Queue","Stack","Deque","Array"]',1,'PDA extends finite automata with a stack (LIFO) for unbounded memory. The stack allows PDA to recognize context-free languages like {a^n b^n} that require counting.','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Automata','medium','The complement of a regular language is:','["Not regular","Regular","Context-free","Undecidable"]',1,'Regular languages are closed under complementation — if L is regular, its complement (Σ* - L) is also regular. Simply swap accepting and non-accepting states in the DFA.','Theory of Computation - Peter Linz',2023),

('GATE','Theory of Computation','Turing Machines','hard','Rice theorem states that:','["All properties of Turing machines are decidable","Any non-trivial semantic property of Turing machine languages is undecidable","Context-free languages are decidable","Regular languages are undecidable"]',1,'Rice theorem: every non-trivial property of the language recognized by a Turing machine is undecidable. A property is non-trivial if some TMs have it and some do not. Powerful generalization of undecidability results.','Theory of Computation - Peter Linz',2023),

-- COMPILER DESIGN (36 questions)
('GATE','Compiler Design','Lexical Analysis','medium','The first phase of a compiler is:','["Syntax analysis","Lexical analysis","Semantic analysis","Code generation"]',1,'Compilation phases: Lexical Analysis → Syntax Analysis (Parsing) → Semantic Analysis → Intermediate Code Generation → Optimization → Code Generation. Lexical analysis (scanning) is first.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Parsing','hard','An LR(0) parser uses:','["One token lookahead","No lookahead (only stack contents)","Two token lookahead","Stack and input only with no lookahead tables"]',1,'LR(0) parsing makes shift/reduce decisions based only on the current state (stack contents) with no lookahead. LR(1) uses one token lookahead. SLR(1) uses LR(0) automaton with 1-token lookahead using FOLLOW sets.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Lexical Analysis','medium','Regular expressions are used in lexical analysis to:','["Parse the grammar","Specify patterns for tokens","Generate machine code","Allocate registers"]',1,'Regular expressions define patterns for tokens (identifiers, keywords, operators, literals). The lexer (scanner) uses these patterns (typically implemented as DFA) to recognize and tokenize the input.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Parsing','hard','FIRST(α) set in a grammar contains:','["Non-terminals that appear in α","Terminals that begin strings derived from α","All symbols derivable from α","Productions of α"]',1,'FIRST(α) is the set of terminals that can begin strings derivable from α (including ε if α can derive the empty string). Used in LL(1) parsing table construction.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Code Optimization','hard','Dead code elimination removes:','["Code that is never executed","Code with high execution frequency","Loop optimizations","Register allocations"]',0,'Dead code elimination removes code that can never be executed (unreachable code after unconditional branch) or whose results are never used. It reduces code size and execution time.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Parsing','hard','An LL(1) grammar must not have:','["Only left recursion","Left recursion or common prefixes (ambiguity)","Right recursion","Productions with ε"]',1,'LL(1) parsers cannot handle: (1) left recursion (causes infinite loop in top-down parsing) and (2) common prefixes causing ambiguity in prediction. Left factoring eliminates common prefixes; recursion elimination handles left recursion.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Intermediate Code','medium','Three-address code is a form of intermediate representation where:','["Each instruction has at most 3 operands","Instructions operate on memory only","Instructions take 3 memory accesses","All instructions are 3 bytes long"]',0,'Three-address code: each statement has at most three operands (two sources, one destination). Form: x = y op z. Facilitates optimization and code generation.','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Compiler Design','Code Optimization','hard','Loop invariant code motion:','["Removes loops","Moves code that produces same result each iteration outside the loop","Unrolls loops","Parallelizes loops"]',1,'Loop invariant code motion moves computations whose results do not change across loop iterations to before the loop (preheader). Reduces redundant computation within loops.','Compilers: Principles, Techniques & Tools - Aho',2023),

-- DIGITAL LOGIC & COMPUTER ORGANIZATION (20 questions)
('GATE','Computer Organization','Number Systems','medium','The two complement of 8-bit binary number 10110110 is:','["01001010","01001001","01001000","00110110"]',0,'Two complement: invert all bits → 01001001, then add 1 → 01001010. Alternatively: find rightmost 1, invert all bits to its left.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Memory','hard','Cache memory uses which principle for efficiency?','["Locality of reference (temporal and spatial)","Large cache size","DRAM technology","Virtual memory mapping"]',0,'Cache efficiency relies on locality of reference: temporal locality (recently accessed data will be accessed again soon) and spatial locality (data near recently accessed data will be accessed soon).','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Instruction Set','medium','RISC architecture is characterized by:','["Complex variable-length instructions","Simple fixed-length instructions, load-store architecture","Hardware-heavy design","Microcode implementation"]',1,'RISC (Reduced Instruction Set Computer): simple fixed-length instructions, load-store architecture (only load/store access memory), large register file, hardwired control. CISC has complex variable-length instructions.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Digital Circuits','hard','The minimum number of NAND gates required to implement an XOR gate is:','["4","5","3","6"]',0,'XOR using NAND: A XOR B = ((A NAND B) NAND (A NAND (A NAND B))) NAND ((A NAND B) NAND (B NAND (A NAND B))). Requires 4 NAND gates.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Pipeline','hard','Pipeline hazards include all of the following EXCEPT:','["Data hazards","Control hazards","Structural hazards","Cache hazards"]',3,'Pipeline hazards: (1) Structural hazards — resource conflicts; (2) Data hazards — instruction depends on previous; (3) Control hazards — branch/jump uncertainty. "Cache hazards" is not a standard classification.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Number Systems','medium','The hexadecimal number FF in decimal is:','["255","256","127","128"]',0,'FF hex = 15×16 + 15 = 240 + 15 = 255 decimal. This is also 2^8 - 1 = 255, the maximum value of an unsigned 8-bit integer.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Digital Circuits','medium','De Morgan theorem states:','["NOT(A AND B) = NOT A OR NOT B","NOT(A AND B) = NOT A AND NOT B","NOT(A OR B) = NOT A AND NOT B","Both A and C"]',3,'De Morgan laws: NOT(A AND B) = NOT A OR NOT B (NAND = NOR of complements), and NOT(A OR B) = NOT A AND NOT B (NOR = NAND of complements). Both A and C are De Morgan theorems.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Memory','hard','Virtual memory allows:','["Programs larger than physical RAM to run","Faster execution than RAM","Replacing cache","Direct disk access"]',0,'Virtual memory creates an abstraction of a larger address space than physical RAM using disk storage. The OS manages mapping between virtual and physical addresses via page tables, enabling programs larger than RAM to execute.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Computer Organization','Pipeline','medium','CPI (Cycles Per Instruction) ideal for a 5-stage pipeline is:','["5","1","0.5","2"]',1,'An ideal pipeline with n stages executes one instruction per cycle (CPI=1) after the pipeline is filled. Pipeline stalls (due to hazards) increase effective CPI above 1.','Computer Organization - Patterson & Hennessy',2023),

('GATE','Data Structures','Trees','hard','B-tree of order m means each non-root node has at least:','["m/2 keys","ceil(m/2)-1 keys","m-1 keys","ceil(m/2) children"]',1,'B-tree of order m: each non-root node has at least ceil(m/2)-1 keys and at most m-1 keys. Root has at least 1 key. Used in databases and file systems for efficient disk access.','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Dynamic Programming','hard','Matrix chain multiplication with n matrices has how many subproblems?','["O(n)","O(n²)","O(n³)","O(2^n)"]',1,'Matrix chain multiplication considers all possible ways to split sequences of matrices. Number of distinct subproblems = O(n²) (all pairs i,j where i≤j). Total time O(n³).','GATE Computer Science - Arihant',2023),

('GATE','Operating Systems','Process Management','hard','Which of the following is a preemptive scheduling algorithm?','["FCFS","SJF (non-preemptive)","SRTF (Shortest Remaining Time First)","Priority (non-preemptive)"]',2,'SRTF (Shortest Remaining Time First) is the preemptive version of SJF. When a new process arrives with shorter remaining time than the current process, it preempts and runs instead.','Operating Systems - Galvin',2023),

('GATE','DBMS','SQL','hard','The SQL query to find the second highest salary is:','["SELECT MAX(salary) FROM emp","SELECT MAX(salary) FROM emp WHERE salary NOT IN (SELECT MAX(salary) FROM emp)","SELECT salary FROM emp ORDER BY salary DESC LIMIT 1 OFFSET 1","SELECT TOP 2 salary FROM emp"]',1,'SELECT MAX(salary) FROM emp WHERE salary NOT IN (SELECT MAX(salary) FROM emp) finds the maximum salary excluding the highest — which is the second highest.','Database System Concepts - Silberschatz',2023),

('GATE','Computer Networks','Network Layer','hard','IPv6 address length is:','["32 bits","64 bits","128 bits","256 bits"]',2,'IPv6 uses 128-bit addresses (written as 8 groups of 4 hexadecimal digits, e.g., 2001:0db8:85a3:0000:0000:8a2e:0370:7334), compared to IPv4 which uses 32-bit addresses.','Computer Networks - Tanenbaum',2023),

('GATE','Theory of Computation','Automata','hard','The language accepted by a finite automaton is always:','["Context-sensitive","Context-free","Regular","Recursively enumerable"]',2,'By definition, finite automata (DFA, NFA, ε-NFA) accept exactly the class of regular languages. This is one of the fundamental results of formal language theory.','Theory of Computation - Peter Linz',2023),

('GATE','Compiler Design','Parsing','medium','Shift-reduce conflict in LR parsing means:','["The parser cannot shift","The parser cannot determine whether to shift or reduce","The parser stack is empty","The grammar is ambiguous"]',1,'Shift-reduce conflict: given the current state and lookahead token, the parser cannot decide whether to shift (push token) or reduce (apply a production). Indicates grammar is not SLR(1)/LR(1).','Compilers: Principles, Techniques & Tools - Aho',2023),

('GATE','Data Structures','Graphs','hard','Strongly Connected Components (SCCs) of a directed graph can be found in:','["O(V + E) using Kosaraju or Tarjan algorithms","O(V²)","O(V × E)","O(E log V)"]',0,'SCCs can be found in linear time O(V + E) using Kosaraju algorithm (two DFS passes) or Tarjan algorithm (single DFS with stack and low-link values).','GATE Computer Science - Arihant',2023),

('GATE','Algorithms','Complexity','hard','If every NP problem can be solved in polynomial time, then:','["P = NP","P ≠ NP","NP-complete problems are unsolvable","Exponential algorithms are needed"]',0,'If every NP problem (problems where solutions can be verified in polynomial time) can also be SOLVED in polynomial time, then P = NP. This is the most famous open problem in computer science.','GATE Computer Science - Arihant',2023),

('GATE','Operating Systems','File Systems','hard','Journaling file systems (like ext4) maintain:','["A backup copy of all files","A log of changes before committing to the main file system","Redundant data on multiple disks","File compression data"]',1,'Journaling file systems maintain a journal (log) of pending changes. Before writing to the main file system, changes are written to the journal. If a crash occurs, the journal is replayed on recovery, ensuring consistency.','Operating Systems - Galvin',2023),

('GATE','DBMS','Transactions','hard','Lost update problem in databases occurs when:','["A transaction reads stale data","Two transactions read the same data and one overwrites the other changes","A transaction fails to commit","Deadlock occurs"]',1,'Lost update: T1 reads X, T2 reads X, T1 writes X (new value), T2 writes X (based on old value) — T1 update is lost. Prevented by locking or using optimistic concurrency control.','Database System Concepts - Silberschatz',2023);
