import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { FileText, Clock, ArrowRight, Loader2 } from "lucide-react";
import { listTests } from "@/lib/tests.functions";

export const Route = createFileRoute("/_app/mock-tests")({
  component: MockTests,
  head: () => ({
    meta: [
      { title: "NEET PG Tests — Meritus" },
      { name: "description", content: "Live NEET PG mock tests, daily quizzes and subject-wise practice — backed by AI-generated questions." },
    ],
  }),
});

const labels: Record<string, { label: string; tone: string }> = {
  daily: { label: "Daily Quiz", tone: "bg-teal-light text-teal" },
  subject: { label: "Subject Test", tone: "bg-primary-light text-primary" },
  grand: { label: "Grand Test", tone: "bg-gold-light text-gold" },
};

function MockTests() {
  const fetchTests = useServerFn(listTests);
  const { data, isLoading, error } = useQuery({
    queryKey: ["tests", "neet_pg"],
    queryFn: () => fetchTests(),
  });

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-body">NEET PG Tests</h1>
        <p className="text-sm text-secondary-text mt-1">
          Live, AI-augmented question bank. New questions can be generated by admins from the Admin page.
        </p>
      </div>

      {isLoading && (
        <div className="flex items-center gap-2 text-secondary-text"><Loader2 className="animate-spin" size={16} /> Loading tests…</div>
      )}
      {error && <div className="text-danger text-sm">Failed to load tests: {(error as Error).message}</div>}

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {(data ?? []).map((t) => {
          const meta = labels[t.test_type] ?? { label: t.test_type, tone: "bg-muted text-secondary-text" };
          const empty = !t.question_count;
          return (
            <div key={t.id} className="bg-card border border-border rounded-xl p-5 shadow-card hover:border-indigo-200 hover:shadow-card-hover hover:-translate-y-0.5 transition-all flex flex-col">
              <div className="flex items-center justify-between">
                <span className={`text-xs font-bold px-2 py-1 rounded-md ${meta.tone}`}>{meta.label}</span>
                <span className="text-xs font-bold px-2 py-1 rounded-full bg-primary-light text-primary">NEET PG</span>
              </div>
              <h3 className="mt-3 font-semibold text-body">{t.title}</h3>
              <p className="mt-1.5 text-sm text-secondary-text line-clamp-2">{t.description}</p>
              <div className="mt-4 flex items-center gap-4 text-xs text-secondary-text">
                <span className="inline-flex items-center gap-1"><FileText size={13} /> {t.question_count} questions</span>
                <span className="inline-flex items-center gap-1"><Clock size={13} /> {t.duration_min} min</span>
              </div>
              <div className="mt-5 pt-4 border-t border-border flex items-center justify-between">
                <span className="text-xs font-medium px-2.5 py-1 rounded-md bg-muted text-secondary-text">+{t.marks_per_correct}/{t.marks_per_wrong}</span>
                {empty ? (
                  <Button size="sm" disabled variant="outline">No questions yet</Button>
                ) : (
                  <Link to="/mock-tests/$id" params={{ id: t.id }}>
                    <Button size="sm" className="font-semibold">Start Test <ArrowRight size={14} className="ml-1" /></Button>
                  </Link>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}