import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect } from "react";
import { useNavigate } from "@tanstack/react-router";
import { useAuth } from "@/integrations/external-supabase/auth-context";
import { Button } from "@/components/ui/button";
import {
  Brain, Monitor, Sparkles, CalendarDays, TrendingUp, Users,
  Check, Star, ArrowRight, X,
} from "lucide-react";
import heroStudent from "@/assets/hero-student.jpg";

export const Route = createFileRoute("/")({
  component: Landing,
  head: () => ({
    meta: [
      { title: "Meritus — Crack any exam with AI by your side" },
      { name: "description", content: "India's first AI-powered all-exam platform. Prep for JEE, NEET, UPSC, Banking, GATE, CAT and 200+ exams." },
      { property: "og:title", content: "Meritus — Crack any exam with AI by your side" },
      { property: "og:description", content: "India's first AI-powered all-exam platform. Prep for JEE, NEET, UPSC, Banking, GATE, CAT and 200+ exams." },
      { property: "og:url", content: "https://meritusbeta.lovable.app/" },
      { property: "og:type", content: "website" },
    ],
    links: [{ rel: "canonical", href: "https://meritusbeta.lovable.app/" }],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Organization",
          name: "Meritus",
          url: "https://meritusbeta.lovable.app/",
          logo: "https://meritusbeta.lovable.app/favicon.ico",
          description: "AI-powered competitive exam prep for JEE, NEET, UPSC, Banking, GATE, CAT and 200+ exams.",
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebSite",
          name: "Meritus",
          url: "https://meritusbeta.lovable.app/",
          potentialAction: {
            "@type": "SearchAction",
            target: "https://meritusbeta.lovable.app/?q={search_term_string}",
            "query-input": "required name=search_term_string",
          },
        }),
      },
    ],
  }),
});

const examPills = ["JEE Main", "NEET UG", "UPSC CSE", "GATE", "CAT", "SSC CGL", "IBPS PO", "CUET"];

const features = [
  { icon: Brain, color: "teal", title: "Forget-Meter AI", desc: "Ebbinghaus forgetting curve tracks exactly when you'll forget each topic.", to: "/forget-meter" as const },
  { icon: Monitor, color: "primary", title: "NTA Exam Simulator", desc: "Pixel-perfect replica of the actual JEE/NEET interface with real-time timer.", to: "/mock-tests" as const },
  { icon: Sparkles, color: "gold", title: "ExamMatch AI", desc: "Claude AI analyses your profile and recommends the best-fit exams for you.", to: "/ai-tutor" as const },
  { icon: CalendarDays, color: "purple", title: "AI Study Planner", desc: "Personalised week-by-week study schedule generated by AI.", to: "/study-planner" as const },
  { icon: TrendingUp, color: "success", title: "Rank Predictor", desc: "Know your expected rank before the result.", to: "/leaderboard" as const },
  { icon: Users, color: "blue", title: "Mentor Connect", desc: "1-on-1 sessions with toppers who cracked your target exam.", to: "/mentor-sessions" as const },
];

const colorMap: Record<string, string> = {
  teal: "bg-teal-light text-teal",
  primary: "bg-primary-light text-primary",
  gold: "bg-gold-light text-gold",
  purple: "bg-violet-50 text-violet-600",
  success: "bg-success-light text-success",
  blue: "bg-sky-50 text-sky-600",
};

const testimonials = [
  { name: "Priya Sharma", exam: "JEE Advanced 2024", rank: "AIR 287", quote: "Forget-Meter literally changed how I revise. I stopped wasting time on topics I already knew." },
  { name: "Arjun Patel", exam: "NEET UG 2024", rank: "Score 681/720", quote: "The NTA simulator made the real exam feel like just another mock. Zero anxiety on the day." },
  { name: "Sneha Reddy", exam: "UPSC CSE 2023", rank: "AIR 142", quote: "ExamMatch AI helped me realise UPSC was the right fit. Mentor sessions were gold." },
];

const plans = [
  {
    name: "Free", price: "₹0", sub: "Forever", cta: "Start free", featured: false,
    features: [["3 mock tests / month", true], ["Basic analytics", true], ["ExamMatch AI", true], ["AI Study Planner", false], ["Forget-Meter", false], ["Mentor sessions", false]],
  },
  {
    name: "Pro", price: "₹499", sub: "/month", cta: "Go Pro", featured: true,
    features: [["Unlimited mock tests", true], ["Full analytics", true], ["ExamMatch AI", true], ["AI Study Planner", true], ["Forget-Meter", true], ["Mentor sessions", false]],
  },
  {
    name: "Power", price: "₹999", sub: "/month", cta: "Get Power", featured: false,
    features: [["Everything in Pro", true], ["1-on-1 Mentor sessions", true], ["Voice AI tutor", true], ["Priority support", true], ["Custom study plan", true], ["Early-access features", true]],
  },
];

function Landing() {
  const { user, loading } = useAuth();
  const nav = useNavigate();
  useEffect(() => {
    if (!loading && user) nav({ to: "/dashboard" });
  }, [loading, user, nav]);

  return (
    <div className="min-h-screen bg-background">
      {/* Top nav */}
      <header className="absolute top-0 inset-x-0 z-20">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="h-9 w-9 rounded-md bg-primary flex items-center justify-center font-bold text-white">M</div>
            <div className="flex flex-col leading-tight">
              <span className="font-bold text-lg text-white">Meritus</span>
              <span className="text-[10px] uppercase tracking-[0.18em] text-indigo-200">Merit, Mastered.</span>
            </div>
          </Link>
          <nav className="hidden md:flex items-center gap-7 text-sm text-indigo-100">
            <a href="#features" className="hover:text-white">Features</a>
            <a href="#pricing" className="hover:text-white">Pricing</a>
            <Link to="/leaderboard" className="hover:text-white">Leaderboard</Link>
          </nav>
          <div className="flex items-center gap-2">
            <Link to="/login"><Button variant="ghost" className="text-white hover:bg-white/10 hover:text-white">Log in</Button></Link>
            <Link to="/signup"><Button className="bg-white text-navy hover:bg-white/90 font-semibold">Sign up</Button></Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-br from-navy via-navy to-navy-2 text-white pt-28 pb-24">
        <div className="absolute inset-0 bg-dot-grid opacity-60" />
        {/* floating pills */}
        {examPills.map((p, i) => (
          <span
            key={p}
            className="hidden lg:block absolute text-xs font-semibold px-3 py-1.5 rounded-full bg-white/10 border border-white/15 backdrop-blur-sm text-indigo-100"
            style={{
              top: `${15 + (i % 4) * 18}%`,
              left: i < 4 ? `${4 + i * 2}%` : undefined,
              right: i >= 4 ? `${4 + (i - 4) * 2}%` : undefined,
              animation: `float ${5 + (i % 3)}s ease-in-out ${i * 0.4}s infinite`,
            }}
          >
            {p}
          </span>
        ))}

        <div className="relative max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-12 items-center">
          <div className="text-center lg:text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/10 border border-white/15 text-xs font-medium">
            <Star size={12} className="text-gold fill-gold" />
            India's First AI-Powered All-Exam Platform
            <span className="px-1.5 py-0.5 rounded-full bg-gold/20 text-gold text-[10px] font-bold">BETA</span>
          </div>
          <h1 className="mt-6 text-5xl md:text-[56px] font-bold leading-[1.05] tracking-tight">
            Crack any exam with
            <br />
            <span className="text-gradient-hero">AI by your side.</span>
          </h1>
          <p className="mt-6 text-lg text-indigo-200 max-w-2xl mx-auto lg:mx-0">
            Prep for JEE, NEET, UPSC, Banking, GATE, CAT and 200+ Indian competitive exams — all in one
            AI-first platform built for Indian aspirants.
          </p>
          <div className="mt-7 flex flex-wrap justify-center lg:justify-start gap-x-6 gap-y-2 text-sm">
            {["Free to start", "All 200+ exams", "AI-powered weak spot detection"].map((t) => (
              <span key={t} className="inline-flex items-center gap-2 text-indigo-100">
                <Check size={16} className="text-emerald-400" /> {t}
              </span>
            ))}
          </div>
          <div className="mt-9 flex flex-wrap justify-center lg:justify-start gap-3">
            <Link to="/signup">
              <Button size="lg" className="bg-white text-navy hover:bg-white/90 font-bold h-12 px-7">
                Start for free <ArrowRight className="ml-2" size={16} />
              </Button>
            </Link>
            <Button size="lg" variant="outline" className="border-white/40 text-white hover:bg-white/10 hover:text-white bg-transparent h-12 px-7">
              See how it works
            </Button>
          </div>
          </div>

          {/* Hero image */}
          <div className="relative mx-auto lg:mx-0 w-full max-w-xl">
            <div className="absolute -inset-6 bg-gradient-to-tr from-primary/40 via-violet-500/20 to-gold/30 blur-3xl rounded-full opacity-70" />
            <div className="relative rounded-2xl overflow-hidden border border-white/15 shadow-[0_25px_70px_-15px_rgba(0,0,0,0.6)] ring-1 ring-white/10">
              <img
                src={heroStudent}
                alt="Indian student preparing for competitive exams with Meritus AI"
                width={1024}
                height={1024}
                className="w-full h-auto block"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-navy/60 via-transparent to-transparent" />
            </div>
            {/* floating badge */}
            <div className="hidden sm:flex absolute -bottom-5 -left-5 items-center gap-3 rounded-xl bg-white text-navy px-4 py-3 shadow-xl">
              <div className="h-9 w-9 rounded-full bg-gold-light flex items-center justify-center">
                <Star size={16} className="text-gold fill-gold" />
              </div>
              <div className="text-left">
                <div className="text-sm font-bold leading-none">AIR 287</div>
                <div className="text-[11px] text-secondary-text mt-1">JEE Adv 2024</div>
              </div>
            </div>
            <div className="hidden sm:flex absolute -top-4 -right-4 items-center gap-2 rounded-xl bg-white text-navy px-3 py-2 shadow-xl">
              <div className="h-8 w-8 rounded-lg bg-teal-light flex items-center justify-center">
                <TrendingUp size={14} className="text-teal" />
              </div>
              <div className="text-left">
                <div className="text-xs font-bold leading-none">+47% rank</div>
                <div className="text-[10px] text-secondary-text mt-0.5">in 90 days</div>
              </div>
            </div>
          </div>
        </div>

        <div className="relative max-w-5xl mx-auto px-6 mt-16 text-center">

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              ["3.8 Cr+", "Aspirants"],
              ["200+", "Exams"],
              ["AI-First", "Platform"],
              ["99.2%", "Accuracy"],
            ].map(([n, l]) => (
              <div key={l} className="rounded-xl bg-white/5 border border-white/10 backdrop-blur-sm p-5">
                <div className="text-2xl md:text-3xl font-bold text-white">{n}</div>
                <div className="text-xs text-indigo-200 mt-1">{l}</div>
              </div>
            ))}
          </div>

          {/* Feature pills */}
          <div className="mt-12 flex flex-wrap justify-center gap-2">
            {["Forget-Meter AI", "ExamMatch AI", "Rank Predictor", "NTA UI Simulator"].map((f) => (
              <span key={f} className="text-xs font-medium px-3 py-1.5 rounded-full bg-white/10 border border-white/15 text-indigo-100">
                {f}
              </span>
            ))}
          </div>
        </div>

        {/* fade */}
        <div className="absolute bottom-0 inset-x-0 h-24 bg-gradient-to-b from-transparent to-background" />
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <span className="label-caps text-primary">Features</span>
            <h2 className="mt-2 text-3xl md:text-4xl font-bold text-body">Everything you need to crack your exam</h2>
            <p className="mt-3 text-secondary-text max-w-2xl mx-auto">
              Built for Indian aspirants by toppers and AI engineers. Every feature designed to maximise your rank.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f) => {
              const Icon = f.icon;
              return (
                <Link key={f.title} to={f.to} className="group block bg-card border border-border rounded-xl p-6 shadow-card hover:border-indigo-200 hover:shadow-[0_8px_25px_rgba(67,56,202,0.15)] hover:-translate-y-0.5 transition-all">
                  <div className={`h-11 w-11 rounded-lg flex items-center justify-center ${colorMap[f.color]}`}>
                    <Icon size={22} />
                  </div>
                  <h3 className="mt-4 text-lg font-semibold text-body">{f.title}</h3>
                  <p className="mt-2 text-sm text-secondary-text leading-relaxed">{f.desc}</p>
                </Link>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="bg-navy py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <span className="label-caps text-indigo-300">Testimonials</span>
            <h2 className="mt-2 text-3xl md:text-4xl font-bold text-white">Trusted by India's top aspirants</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {testimonials.map((t) => (
              <div key={t.name} className="rounded-xl bg-white/[0.06] border border-white/10 p-6 backdrop-blur-sm">
                <div className="flex gap-0.5 text-gold mb-4">
                  {Array.from({ length: 5 }).map((_, i) => <Star key={i} size={14} className="fill-gold" />)}
                </div>
                <p className="text-indigo-100 text-sm leading-relaxed">"{t.quote}"</p>
                <div className="mt-5 flex items-center gap-3">
                  <div className="h-10 w-10 rounded-full bg-gradient-to-br from-indigo-400 to-violet-500 flex items-center justify-center font-bold text-white text-sm">
                    {t.name.split(" ").map((n) => n[0]).join("")}
                  </div>
                  <div>
                    <div className="text-white font-semibold text-sm">{t.name}</div>
                    <div className="text-indigo-300 text-xs">{t.exam} · {t.rank}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <span className="label-caps text-primary">Pricing</span>
            <h2 className="mt-2 text-3xl md:text-4xl font-bold text-body">Simple, transparent pricing</h2>
            <p className="mt-3 text-secondary-text">Start free. Upgrade when you're ready to commit.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {plans.map((p) => (
              <div
                key={p.name}
                className={`relative rounded-xl bg-card p-7 shadow-card border ${
                  p.featured ? "border-primary border-2 shadow-[0_8px_25px_rgba(67,56,202,0.15)]" : "border-border"
                }`}
              >
                {p.featured && (
                  <span className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-primary text-white text-xs font-bold">
                    MOST POPULAR
                  </span>
                )}
                <h3 className="text-lg font-semibold text-body">{p.name}</h3>
                <div className="mt-4 flex items-baseline gap-1">
                  <span className="text-4xl font-bold text-body">{p.price}</span>
                  <span className="text-secondary-text text-sm">{p.sub}</span>
                </div>
                <Link to="/signup">
                  <Button className={`mt-6 w-full ${p.featured ? "" : "bg-card border border-primary text-primary hover:bg-primary-light"}`}>
                    {p.cta}
                  </Button>
                </Link>
                <ul className="mt-6 space-y-3 text-sm">
                  {p.features.map(([feat, on]) => (
                    <li key={String(feat)} className="flex items-start gap-2">
                      {on ? <Check size={16} className="text-success mt-0.5 shrink-0" /> : <X size={16} className="text-muted-text mt-0.5 shrink-0" />}
                      <span className={on ? "text-body" : "text-muted-text"}>{feat}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-navy py-20 px-6 text-center">
        <h2 className="text-3xl md:text-4xl font-bold text-white">Start your merit journey today</h2>
        <p className="mt-3 text-indigo-200">Join 3.8 crore aspirants already preparing smarter.</p>
        <div className="mt-7 flex flex-wrap justify-center gap-3">
          <Link to="/signup"><Button size="lg" className="bg-white text-navy hover:bg-white/90 font-bold h-12 px-7">Start for free</Button></Link>
          <Button size="lg" variant="outline" className="border-white/40 text-white bg-transparent hover:bg-white/10 hover:text-white h-12 px-7">Talk to an expert</Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#0F0D2E] text-indigo-200 px-6 py-14">
        <div className="max-w-6xl mx-auto grid md:grid-cols-5 gap-8 text-sm">
          <div className="md:col-span-2">
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-md bg-primary flex items-center justify-center font-bold text-white">M</div>
              <span className="font-bold text-white">Meritus</span>
            </div>
            <p className="mt-3 text-indigo-300/80 max-w-sm">Merit, Mastered. India's AI-powered competitive exam preparation platform.</p>
          </div>
          {[
            ["Product", ["Features", "Pricing", "Mock Tests", "AI Tutor"]],
            ["Exams", ["JEE", "NEET", "UPSC", "GATE", "CAT"]],
            ["Company", ["About", "Careers", "Blog", "Press"]],
          ].map(([h, items]) => (
            <div key={h as string}>
              <h4 className="text-white font-semibold mb-3">{h as string}</h4>
              <ul className="space-y-2">
                {(items as string[]).map((i) => <li key={i}><a href="#" className="hover:text-white">{i}</a></li>)}
              </ul>
            </div>
          ))}
        </div>
        <div className="max-w-6xl mx-auto mt-10 pt-6 border-t border-white/10 text-xs text-indigo-300/70 flex justify-between">
          <span>© 2025 Meritus. All rights reserved.</span>
          <span>Made in India 🇮🇳</span>
        </div>
      </footer>
    </div>
  );
}
