/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUpgradeRouteImport } from './routes/_app.upgrade'
import { Route as AppStudyPlannerRouteImport } from './routes/_app.study-planner'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMyExamsRouteImport } from './routes/_app.my-exams'
import { Route as AppMockTestsRouteImport } from './routes/_app.mock-tests'
import { Route as AppMentorSessionsRouteImport } from './routes/_app.mentor-sessions'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppForgetMeterRouteImport } from './routes/_app.forget-meter'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiTutorRouteImport } from './routes/_app.ai-tutor'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyPlannerRoute = AppStudyPlannerRouteImport.update({
  id: '/study-planner',
  path: '/study-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMyExamsRoute = AppMyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => AppRoute,
} as any)
const AppMockTestsRoute = AppMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorSessionsRoute = AppMentorSessionsRouteImport.update({
  id: '/mentor-sessions',
  path: '/mentor-sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppForgetMeterRoute = AppForgetMeterRouteImport.update({
  id: '/forget-meter',
  path: '/forget-meter',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTutorRoute = AppAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-tutor': typeof AppAiTutorRoute
  '/dashboard': typeof AppDashboardRoute
  '/forget-meter': typeof AppForgetMeterRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/mentor-sessions': typeof AppMentorSessionsRoute
  '/mock-tests': typeof AppMockTestsRoute
  '/my-exams': typeof AppMyExamsRoute
  '/profile': typeof AppProfileRoute
  '/study-planner': typeof AppStudyPlannerRoute
  '/upgrade': typeof AppUpgradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-tutor': typeof AppAiTutorRoute
  '/dashboard': typeof AppDashboardRoute
  '/forget-meter': typeof AppForgetMeterRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/mentor-sessions': typeof AppMentorSessionsRoute
  '/mock-tests': typeof AppMockTestsRoute
  '/my-exams': typeof AppMyExamsRoute
  '/profile': typeof AppProfileRoute
  '/study-planner': typeof AppStudyPlannerRoute
  '/upgrade': typeof AppUpgradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/ai-tutor': typeof AppAiTutorRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forget-meter': typeof AppForgetMeterRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/mentor-sessions': typeof AppMentorSessionsRoute
  '/_app/mock-tests': typeof AppMockTestsRoute
  '/_app/my-exams': typeof AppMyExamsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/study-planner': typeof AppStudyPlannerRoute
  '/_app/upgrade': typeof AppUpgradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/ai-tutor'
    | '/dashboard'
    | '/forget-meter'
    | '/leaderboard'
    | '/mentor-sessions'
    | '/mock-tests'
    | '/my-exams'
    | '/profile'
    | '/study-planner'
    | '/upgrade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/ai-tutor'
    | '/dashboard'
    | '/forget-meter'
    | '/leaderboard'
    | '/mentor-sessions'
    | '/mock-tests'
    | '/my-exams'
    | '/profile'
    | '/study-planner'
    | '/upgrade'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/ai-tutor'
    | '/_app/dashboard'
    | '/_app/forget-meter'
    | '/_app/leaderboard'
    | '/_app/mentor-sessions'
    | '/_app/mock-tests'
    | '/_app/my-exams'
    | '/_app/profile'
    | '/_app/study-planner'
    | '/_app/upgrade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study-planner': {
      id: '/_app/study-planner'
      path: '/study-planner'
      fullPath: '/study-planner'
      preLoaderRoute: typeof AppStudyPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-exams': {
      id: '/_app/my-exams'
      path: '/my-exams'
      fullPath: '/my-exams'
      preLoaderRoute: typeof AppMyExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock-tests': {
      id: '/_app/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof AppMockTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentor-sessions': {
      id: '/_app/mentor-sessions'
      path: '/mentor-sessions'
      fullPath: '/mentor-sessions'
      preLoaderRoute: typeof AppMentorSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forget-meter': {
      id: '/_app/forget-meter'
      path: '/forget-meter'
      fullPath: '/forget-meter'
      preLoaderRoute: typeof AppForgetMeterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-tutor': {
      id: '/_app/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AppAiTutorRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiTutorRoute: typeof AppAiTutorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppForgetMeterRoute: typeof AppForgetMeterRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMentorSessionsRoute: typeof AppMentorSessionsRoute
  AppMockTestsRoute: typeof AppMockTestsRoute
  AppMyExamsRoute: typeof AppMyExamsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStudyPlannerRoute: typeof AppStudyPlannerRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiTutorRoute: AppAiTutorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppForgetMeterRoute: AppForgetMeterRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMentorSessionsRoute: AppMentorSessionsRoute,
  AppMockTestsRoute: AppMockTestsRoute,
  AppMyExamsRoute: AppMyExamsRoute,
  AppProfileRoute: AppProfileRoute,
  AppStudyPlannerRoute: AppStudyPlannerRoute,
  AppUpgradeRoute: AppUpgradeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
