/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockTestsIdRouteImport } from './routes/mock-tests.$id'
import { Route as AppStudyPlannerRouteImport } from './routes/_app.study-planner'
import { Route as AppMyExamsRouteImport } from './routes/_app.my-exams'
import { Route as AppMockTestsRouteImport } from './routes/_app.mock-tests'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppForgetMeterRouteImport } from './routes/_app.forget-meter'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppResultsIdRouteImport } from './routes/_app.results.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsIdRoute = MockTestsIdRouteImport.update({
  id: '/mock-tests/$id',
  path: '/mock-tests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyPlannerRoute = AppStudyPlannerRouteImport.update({
  id: '/study-planner',
  path: '/study-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppMyExamsRoute = AppMyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => AppRoute,
} as any)
const AppMockTestsRoute = AppMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppForgetMeterRoute = AppForgetMeterRouteImport.update({
  id: '/forget-meter',
  path: '/forget-meter',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsIdRoute = AppResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/forget-meter': typeof AppForgetMeterRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/mock-tests': typeof AppMockTestsRoute
  '/my-exams': typeof AppMyExamsRoute
  '/study-planner': typeof AppStudyPlannerRoute
  '/mock-tests/$id': typeof MockTestsIdRoute
  '/results/$id': typeof AppResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/forget-meter': typeof AppForgetMeterRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/mock-tests': typeof AppMockTestsRoute
  '/my-exams': typeof AppMyExamsRoute
  '/study-planner': typeof AppStudyPlannerRoute
  '/mock-tests/$id': typeof MockTestsIdRoute
  '/results/$id': typeof AppResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forget-meter': typeof AppForgetMeterRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/mock-tests': typeof AppMockTestsRoute
  '/_app/my-exams': typeof AppMyExamsRoute
  '/_app/study-planner': typeof AppStudyPlannerRoute
  '/mock-tests/$id': typeof MockTestsIdRoute
  '/_app/results/$id': typeof AppResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/forget-meter'
    | '/leaderboard'
    | '/mock-tests'
    | '/my-exams'
    | '/study-planner'
    | '/mock-tests/$id'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/forget-meter'
    | '/leaderboard'
    | '/mock-tests'
    | '/my-exams'
    | '/study-planner'
    | '/mock-tests/$id'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/forget-meter'
    | '/_app/leaderboard'
    | '/_app/mock-tests'
    | '/_app/my-exams'
    | '/_app/study-planner'
    | '/mock-tests/$id'
    | '/_app/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  MockTestsIdRoute: typeof MockTestsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/$id': {
      id: '/mock-tests/$id'
      path: '/mock-tests/$id'
      fullPath: '/mock-tests/$id'
      preLoaderRoute: typeof MockTestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/study-planner': {
      id: '/_app/study-planner'
      path: '/study-planner'
      fullPath: '/study-planner'
      preLoaderRoute: typeof AppStudyPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-exams': {
      id: '/_app/my-exams'
      path: '/my-exams'
      fullPath: '/my-exams'
      preLoaderRoute: typeof AppMyExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock-tests': {
      id: '/_app/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof AppMockTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forget-meter': {
      id: '/_app/forget-meter'
      path: '/forget-meter'
      fullPath: '/forget-meter'
      preLoaderRoute: typeof AppForgetMeterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results/$id': {
      id: '/_app/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof AppResultsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppForgetMeterRoute: typeof AppForgetMeterRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMockTestsRoute: typeof AppMockTestsRoute
  AppMyExamsRoute: typeof AppMyExamsRoute
  AppStudyPlannerRoute: typeof AppStudyPlannerRoute
  AppResultsIdRoute: typeof AppResultsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppForgetMeterRoute: AppForgetMeterRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMockTestsRoute: AppMockTestsRoute,
  AppMyExamsRoute: AppMyExamsRoute,
  AppStudyPlannerRoute: AppStudyPlannerRoute,
  AppResultsIdRoute: AppResultsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  MockTestsIdRoute: MockTestsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
